context:
  module_serial: SVR3QA2098
  module_type: MILL
description: 'Komplette MILL-Sequenz: PICK → MILL → DROP'
name: mill_complete_sequence
steps:
- name: PICK
  payload:
    action: PICK
    orderId: '{{orderId}}'
    orderUpdateId: '{{orderUpdateId}}'
  topic: module/v1/ff/{{module_serial}}/order
  wait_condition:
    payload_contains:
      actionState: IDLE
    topic: module/v1/ff/{{module_serial}}/state
- name: MILL
  payload:
    action: MILL
    orderId: '{{orderId}}'
    orderUpdateId: '{{orderUpdateId}}'
  topic: module/v1/ff/{{module_serial}}/order
  wait_condition:
    payload_contains:
      actionState: IDLE
    topic: module/v1/ff/{{module_serial}}/state
- name: DROP
  payload:
    action: DROP
    orderId: '{{orderId}}'
    orderUpdateId: '{{orderUpdateId}}'
  topic: module/v1/ff/{{module_serial}}/order
