import { Uc06SvgGeneratorService } from './uc-06-svg-generator.service';

describe('Uc06SvgGeneratorService', () => {
  it('renders all major lane groups, connections and escapes translated text', () => {
    const service = new Uc06SvgGeneratorService();

    const svg = service.generateSvg({
      'uc06.title': 'Process <Optimization>',
      'uc06.subtitle': 'Recommendations & actions',
      'uc06.outcome': 'Lower cycle time',
      'uc06.footer': 'Generated by ORBIS',
      'uc06.lane.process': 'Process',
      'uc06.lane.shopfloor': 'Shopfloor',
      'uc06.mixed.recommend.sub': 'AI recommendation',
      'uc06.conn.kpis': 'KPIs',
      'uc06.conn.recommendation': 'Recommendation',
      'uc06.conn.action': 'Action',
      'uc06.feedback': 'Feedback',
      'uc06.sf.systemsLabel': 'Systems',
      'uc06.sf.devicesLabel': 'Devices',
      'uc06.mixed.target.mes': 'MES',
      'uc06.mixed.target.erp': 'ERP',
      'uc06.mixed.target.planning': 'Planning',
      // Bullets with symbols verify cleanup via replace(/^[•\\-*]\\s*/, '')
      'uc06.proc.observe.bullets': '• One\n- Two\n* Three',
      'uc06.proc.analyze.bullets': '• A\n- B\n* C',
      'uc06.proc.recommend.bullets': '• D\n- E\n* F',
    });

    expect(svg).toContain('<g id="uc06_col_process">');
    expect(svg).toContain('<g id="uc06_container_mixed">');
    expect(svg).toContain('<g id="uc06_col_shopfloor">');
    expect(svg).toContain('id="uc06_conn_sources_dsp"');
    expect(svg).toContain('id="uc06_conn_target_targets"');
    expect(svg).toContain('id="uc06_feedback"');

    expect(svg).toContain('Process &lt;Optimization&gt;');
    expect(svg).toContain('Recommendations &amp; actions');
    expect(svg).toContain('>One</text>');
    expect(svg).toContain('>Two</text>');
    expect(svg).toContain('>Three</text>');
  });

  it('falls back to i18n key when translation is missing', () => {
    const service = new Uc06SvgGeneratorService();
    const svg = service.generateSvg({});

    expect(svg).toContain('uc06.title');
    expect(svg).toContain('uc06.conn.kpis');
    expect(svg).toContain('uc06.sf.devicesLabel');
  });
});
