metadata:
  category: TXT
  description: TXT Sensor Control Message Template
  template_type: "message_structure_definition"
  last_updated: "2025-08-29"
  version: 3.0.0

# TEMPLATE: Message-Struktur-Definition
template:
  name: "txt/sensor_control"
  description: "TXT Sensor Control - Message Structure Definition"
  semantic_purpose: "TXT-Sensoren steuern"
  
  # SYNTAX: Struktur der Nachricht
  structure:
    required_fields:
      - sensor_type
      - command
      - ts
    optional_fields:
      - parameters
      - target_value
    
    field_definitions:
      sensor_type:
        type: "string"
        pattern: "enum"
        description: "Typ des Sensors"
        validation: "must be valid sensor type"
        
      command:
        type: "string"
        pattern: "enum"
        description: "Sensor-Befehl"
        validation: "must be valid command"
        
      parameters:
        type: "object"
        description: "Sensor-Parameter"
        validation: "optional object with sensor parameters"
        
      target_value:
        type: "number"
        description: "Zielwert für den Sensor"
        validation: "optional number"
        
      ts:
        type: "string"
        pattern: "iso8601"
        description: "Zeitstempel"
        validation: "must be ISO 8601 format"
  
  # SEMANTICS: Validierungsregeln
  validation_rules:
    - "ts muss ISO 8601 Format haben"
    - "sensor_type muss gültiger Sensor-Typ sein"
    - "command muss gültiger Befehl sein"
    - "parameters ist optional"
    - "target_value ist optional"
  
  # VARIABLE FIELDS: Enum-Werte für Generierung
  variable_fields:
    sensor_type:
      type: "enum"
      values: ["bme680", "cam", "ldr", "ultrasonic", "temperature"]
      description: "Typ des Sensors"
      
    command:
      type: "enum"
      values: ["start", "stop", "read", "calibrate", "reset"]
      description: "Sensor-Befehl"
  
  # MQTT INTEGRATION
  mqtt:
    topic_pattern: "/j1/txt/1/c/{sensor_type}"
    direction: "outbound"
    qos: 1
    retain: false
    
  # USAGE EXAMPLES (mehrere Beispiele für ENUM-Werte)
  usage_examples:
    - description: "BME680 Sensor starten (start)"
      topic: "/j1/txt/1/c/bme680"
      payload:
        sensor_type: "bme680"
        command: "start"
        parameters:
          sampling_rate: 1000
          temperature_unit: "celsius"
        ts: "2025-08-29T10:00:00Z"
        
    - description: "Kamera Sensor lesen (read)"
      topic: "/j1/txt/1/c/cam"
      payload:
        sensor_type: "cam"
        command: "read"
        parameters:
          resolution: "640x480"
          quality: 85
        ts: "2025-08-29T10:05:00Z"
        
    - description: "LDR Sensor kalibrieren (calibrate)"
      topic: "/j1/txt/1/c/ldr"
      payload:
        sensor_type: "ldr"
        command: "calibrate"
        parameters:
          calibration_mode: "auto"
          reference_value: 512
        ts: "2025-08-29T10:10:00Z"
        
    - description: "Ultraschall Sensor stoppen (stop)"
      topic: "/j1/txt/1/c/ultrasonic"
      payload:
        sensor_type: "ultrasonic"
        command: "stop"
        parameters:
          reason: "maintenance"
        ts: "2025-08-29T10:15:00Z"
        
    - description: "Temperatur Sensor zurücksetzen (reset)"
      topic: "/j1/txt/1/c/temperature"
      payload:
        sensor_type: "temperature"
        command: "reset"
        parameters:
          reset_type: "soft"
        ts: "2025-08-29T10:20:00Z"
