metadata:
  category: CCU
  description: CCU Control Templates
  icon: 🎮
  last_updated: '2025-08-29'
  sub_category: Control
  version: 3.0.0
templates:
  ccu/control/command:
    category: CCU
    description: Steuerungsbefehle an die CCU
    examples:
    - description: System starten
      payload:
        command: START
        source: dashboard
        timestamp: '2025-08-27T10:30:00.123Z'
    - description: System mit Parametern stoppen
      payload:
        command: STOP
        parameters:
          duration: 2 hours
          reason: Scheduled maintenance
        source: api
        timestamp: '2025-08-27T10:30:00.123Z'
    sub_category: Control
    template_structure:
      command:
        description: Steuerungsbefehl
        enum:
        - START
        - STOP
        - PAUSE
        - RESUME
        - RESET
        - EMERGENCY_STOP
        required: true
        type: string
      parameters:
        description: Optionale Parameter für den Befehl
        required: false
        type: object
      source:
        description: Quelle des Befehls (z.B. 'dashboard', 'api')
        required: false
        type: string
      timestamp:
        description: Zeitstempel des Befehls
        format: ISO 8601
        required: true
        type: string
    validation_rules:
    - command muss in [START, STOP, PAUSE, RESUME, RESET, EMERGENCY_STOP] sein
    - timestamp muss ISO 8601 Format haben
  ccu/control/response:
    category: CCU
    description: Antwort der CCU auf Steuerungsbefehle
    examples:
    - description: Erfolgreicher Start
      payload:
        command: START
        executionTime: '2025-08-27T10:30:01.000Z'
        message: System started successfully
        status: SUCCESS
        timestamp: '2025-08-27T10:30:01.234Z'
    - description: Fehlgeschlagener Befehl
      payload:
        command: STOP
        message: System cannot be stopped while processing orders
        status: FAILED
        timestamp: '2025-08-27T10:30:01.234Z'
    sub_category: Control
    template_structure:
      command:
        description: Ursprünglicher Befehl
        required: true
        type: string
      executionTime:
        description: Zeitstempel der Befehlsausführung
        format: ISO 8601
        required: false
        type: string
      message:
        description: Detaillierte Nachricht
        required: false
        type: string
      status:
        description: Status der Befehlsausführung
        enum:
        - SUCCESS
        - FAILED
        - IN_PROGRESS
        required: true
        type: string
      timestamp:
        description: Zeitstempel der Antwort
        format: ISO 8601
        required: true
        type: string
    validation_rules:
    - status muss in [SUCCESS, FAILED, IN_PROGRESS] sein
    - timestamp muss ISO 8601 Format haben
