metadata:
  category: CCU
  description: CCU State Config Templates
  generated: false
  icon: "🏭"
  last_updated: "2025-08-29"
  sub_category: State
  version: 3.0.0

templates:
  ccu/state/config:
    category: CCU
    description: CCU State Config - Generisch
    semantic_purpose: CCU-Konfigurationsstatus überwachen
    mqtt_topic_pattern: "ccu/state/config"
    template_structure:
      version: "<string>"
      modules: "<array>"
      timestamp: "<datetime>"
    variable_fields:
      version:
        type: string
        description: "CCU-Version"
      modules:
        type: array
        description: "Verfügbare Module"
      timestamp:
        type: datetime
        description: "Timestamp"
    validation_rules:
      - timestamp muss ISO 8601 Format haben
      - version muss gültige Versionsnummer sein
      - modules muss Array von Module-IDs sein
    mqtt_control_usage:
      description: CCU-Konfigurationsstatus abfragen
      example_topic: "ccu/state/config"
      example_payload:
        version: "1.0.0"
        modules: ["SVR3QA2098", "SVR4H73275", "SVR4H76530"]
        timestamp: "2025-08-29T10:00:00Z"
