metadata:
  description: APS System Configuration
  last_updated: '2025-09-26T14:03:16.505253'
  version: 1.0.0
production_settings:
  simultaneous_workpieces: 4
total_duration:
  blue: 553
  red: 560
  white: 580
transport_settings:
  charging_threshold: 10
