dashboard:
  auto_refresh: false
  language: de
  refresh_interval: 5
  theme: light
modules:
  aiqs:
    enabled: true
    name: Qualitätsprüfung
  chrg:
    enabled: true
    name: Ladestation
  dps:
    enabled: true
    name: Warenein- und Ausgang
  drill:
    enabled: true
    name: Bohrer
  hbw:
    enabled: true
    name: Hochregallager
  mill:
    enabled: true
    name: Fräse
mqtt:
  broker: localhost
  client_id: omf_dashboard_replay
  keepalive: 45
  password: ''
  port: 1883
  tls: false
  username: ''
nfc:
  enabled: true
  reader_type: default
  timeout: 30
