# OMF2 Product Catalog Configuration
# Minimale Produktdefinitionen für das CCU Dashboard
# Version: 1.0.0

metadata:
  version: "1.0.0"
  description: "OMF2 product catalog for CCU Dashboard"
  last_updated: "2025-10-04"

# Produktdefinitionen (Reihenfolge: Blau, Weiß, Rot)
products:
  blue:
    id: "BLUE"
    name: "Product Blue"
    color: "#0066CC"
    material: "Plastic"
    description: "Complete machining"
    enabled: true
    icon: "🔵"

  white:
    id: "WHITE"
    name: "Product White"
    color: "#FFFFFF"
    material: "Plastic"
    description: "Drilling + Quality Assurance"
    enabled: true
    icon: "⚪"

  red:
    id: "RED"
    name: "Product Red"
    color: "#CC0000"
    material: "Plastic"
    description: "Milling + Quality Assurance"
    enabled: true
    icon: "🔴"

# Keine Katalog-Metadaten mehr benötigt
