metadata:
  category: CCU
  description: Auto-analyzed template for ccu/set/charge
  last_updated: '2025-09-15'
  source: ccu_template_analyzer
  sub_category: Settings
  version: 0.1.0
templates:
  ccu.settings.charge:
    category: CCU
    description: Template for ccu/set/charge
    direction: outbound
    examples:
    - charge: false
      serialNumber: 5iO4
    - charge: true
      serialNumber: 5iO4
    structure: {}
    sub_category: Settings
    validation:
      field_types: {}
      required_fields: []
