metadata:
  category: Node-RED
  description: Node-RED InstantAction Templates
  icon: ⚡
  last_updated: '2025-08-29'
  sub_category: InstantAction
  version: 3.0.0
templates:
  module/v1/ff/NodeRed/SVR4H73275/instantAction:
    category: Node-RED
    description: Node-RED SVR4H73275 InstantAction
    examples:
    - actions:
      - actionId: 17c6074e-ecb0-4324-a01c-3a736a7f2c09
        actionType: reset
      serialNumber: SVR4H73275
      timestamp: '2025-08-25T07:39:05.727Z'
    - actions:
      - actionId: 532c42ff-458c-4899-bb47-1808e9dbf8c0
        actionType: cancelStorageOrder
      serialNumber: SVR4H73275
      timestamp: '2025-08-26T15:10:41.135Z'
    - actions:
      - actionId: fc991e0d-2a17-4965-9dc0-eba2b6744041
        actionType: cancelStorageOrder
      serialNumber: SVR4H73275
      timestamp: '2025-08-26T15:09:40.541Z'
    - actions:
      - actionId: 75413fb8-df90-4bc9-9172-d0908c86fe85
        actionType: cancelStorageOrder
      serialNumber: SVR4H73275
      timestamp: '2025-08-26T14:49:28.263Z'
    - actions:
      - actionId: 1c0e0e8b-f685-4525-bf07-358e68d3a814
        actionType: cancelStorageOrder
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T09:01:12.580Z'
    module: SVR4H73275
    sub_category: InstantAction
    template_structure:
      actions: <string>
      serialNumber: '[SVR4H73275]'
      timestamp: <datetime>
    validation_rules:
    - serialNumber muss in [SVR4H73275] sein
    - timestamp muss ISO 8601 Format haben
