metadata:
  category: Node-RED
  description: Node-RED State Templates
  icon: 📊
  last_updated: '2025-08-29'
  sub_category: State
  version: 3.0.0
templates:
  ccu/state/dashboard:
    category: Node-RED
    description: Node-RED unknown State
    examples:
    - dashboard_count: 3
      status: active
      timestamp: '2024-01-01T12:00:00Z'
    module: unknown
    sub_category: State
    template_structure:
      dashboard_count: '[3]'
      status: '[active]'
      timestamp: <datetime>
    validation_rules:
    - status muss in [active] sein
    - dashboard_count muss in [3] sein
    - timestamp muss ISO 8601 Format haben
  ccu/state/flows:
    category: Node-RED
    description: Node-RED CCU State
    examples:
    - BLUE:
        steps:
        - DRILL
        - MILL
        - AIQS
      RED:
        steps:
        - MILL
        - AIQS
      WHITE:
        steps:
        - DRILL
        - AIQS
    - BLUE:
        steps:
        - DRILL
        - MILL
        - AIQS
      RED:
        steps:
        - MILL
        - AIQS
      WHITE:
        steps:
        - DRILL
        - AIQS
    - BLUE:
        steps:
        - DRILL
        - MILL
        - AIQS
      RED:
        steps:
        - MILL
        - AIQS
      WHITE:
        steps:
        - DRILL
        - AIQS
    - BLUE:
        steps:
        - DRILL
        - MILL
        - AIQS
      RED:
        steps:
        - MILL
        - AIQS
      WHITE:
        steps:
        - DRILL
        - AIQS
    - BLUE:
        steps:
        - DRILL
        - MILL
        - AIQS
      RED:
        steps:
        - MILL
        - AIQS
      WHITE:
        steps:
        - DRILL
        - AIQS
    module: CCU
    sub_category: State
    template_structure:
      BLUE: '[{''steps'': [''DRILL'', ''MILL'', ''AIQS'']}]'
      RED: '[{''steps'': [''MILL'', ''AIQS'']}]'
      WHITE: '[{''steps'': [''DRILL'', ''AIQS'']}]'
    validation_rules:
    - 'BLUE muss in [{''steps'': [''DRILL'', ''MILL'', ''AIQS'']}] sein'
    - 'RED muss in [{''steps'': [''MILL'', ''AIQS'']}] sein'
    - 'WHITE muss in [{''steps'': [''DRILL'', ''AIQS'']}] sein'
  ccu/state/ui:
    category: Node-RED
    description: Node-RED unknown State
    examples:
    - status: ready
      timestamp: '2024-01-01T12:00:00Z'
      ui_count: 2
    module: unknown
    sub_category: State
    template_structure:
      status: '[ready]'
      timestamp: <datetime>
      ui_count: '[2]'
    validation_rules:
    - status muss in [ready] sein
    - ui_count muss in [2] sein
    - timestamp muss ISO 8601 Format haben
  module/v1/ff/NodeRed/SVR4H73275/state:
    category: Node-RED
    description: Node-RED SVR4H73275 State
    examples:
    - actionState:
        command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        result: PASSED
        state: FINISHED
        timestamp: '2025-08-19T09:19:03.473043Z'
      actionStates:
      - command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755595028336
            - code: 600
              ts: 1755595064912
            - code: 200
              ts: 1755595103032
            state: PROCESSED
            type: RED
            workpieceId: 040a8dca341291
        result: PASSED
        state: FINISHED
        timestamp: '2025-08-19T09:19:03.473043Z'
      batteryState: {}
      errors: []
      headerId: 15
      information: []
      operatingMode: AUTOMATIC
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 11
      paused: false
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:19:03.477244Z'
    - actionState:
        command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        state: RUNNING
        timestamp: '2025-08-19T09:18:41.734745Z'
      actionStates:
      - command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755595028336
            - code: 600
              ts: 1755595064912
            - code: 200
              ts: 1755595103032
            state: PROCESSED
            type: RED
            workpieceId: 040a8dca341291
        state: RUNNING
        timestamp: '2025-08-19T09:18:41.734745Z'
      batteryState: {}
      errors: []
      headerId: 14
      information: []
      operatingMode: AUTOMATIC
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 11
      paused: false
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:18:41.735070Z'
    - actionState:
        command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        state: WAITIING
        timestamp: '2025-08-19T09:18:41.260691Z'
      actionStates:
      - command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755595028336
            - code: 600
              ts: 1755595064912
            - code: 200
              ts: 1755595103032
            state: PROCESSED
            type: RED
            workpieceId: 040a8dca341291
        state: WAITIING
        timestamp: '2025-08-19T09:18:41.260691Z'
      batteryState: {}
      errors: []
      headerId: 13
      information: []
      operatingMode: AUTOMATIC
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 11
      paused: false
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:18:41.261033Z'
    - actionState:
        command: factsheetRequest
        id: SOME_ID
        state: FINISHED
        timestamp: '2025-08-19T09:13:34.536843Z'
      actionStates:
      - command: factsheetRequest
        id: SOME_ID
        state: FINISHED
      batteryState: {}
      errors:
      - errorLevel: WARNING
        errorReferences:
        - orderId: null
        errorType: RESET_WARNING
      headerId: 12
      information: []
      operatingMode: AUTOMATIC
      orderId: ''
      orderUpdateId: 0
      paused: false
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:13:34.533327Z'
    - actionState:
        command: factsheetRequest
        id: SOME_ID
        state: FINISHED
        timestamp: '2025-08-19T09:13:34.536843Z'
      actionStates:
      - command: factsheetRequest
        id: SOME_ID
        state: FINISHED
      batteryState: {}
      errors:
      - errorLevel: WARNING
        errorReferences:
        - orderId: null
        errorType: RESET_WARNING
      headerId: 12
      information: []
      operatingMode: AUTOMATIC
      orderId: ''
      orderUpdateId: 0
      paused: false
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:13:34.533327Z'
    module: SVR4H73275
    sub_category: State
    template_structure:
      actionState: <string>
      actionStates: <string>
      batteryState: '[{}]'
      errors: <string>
      headerId: <string>
      information: '[[]]'
      operatingMode: '[AUTOMATIC]'
      orderId: <string>
      orderUpdateId: <string>
      paused: '[False]'
      serialNumber: '[SVR4H73275]'
      timestamp: <datetime>
    validation_rules:
    - information muss in [[]] sein
    - operatingMode muss in [AUTOMATIC] sein
    - serialNumber muss in [SVR4H73275] sein
    - timestamp muss ISO 8601 Format haben
    - paused muss in [False] sein
    - batteryState muss in [{}] sein
  module/v1/ff/NodeRed/SVR4H76530/state:
    category: Node-RED
    description: Node-RED SVR4H76530 State
    examples:
    - actionState:
        command: CHECK_QUALITY
        id: 7b25fdfb-4a9e-419d-836c-c4348d9d9fd3
        result: PASSED
        state: FINISHED
        timestamp: '2025-08-19T09:18:22.005833Z'
      batteryState: {}
      errors: []
      headerId: 7
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 10
      paused: false
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:22.006119Z'
    - actionState:
        command: CHECK_QUALITY
        id: 7b25fdfb-4a9e-419d-836c-c4348d9d9fd3
        result: PASSED
        state: RUNNING
        timestamp: '2025-08-19T09:18:18.525120Z'
      batteryState: {}
      errors: []
      headerId: 6
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 10
      paused: false
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:21.999763Z'
    - actionState:
        command: CHECK_QUALITY
        id: 7b25fdfb-4a9e-419d-836c-c4348d9d9fd3
        state: RUNNING
        timestamp: '2025-08-19T09:18:18.525120Z'
      batteryState: {}
      errors: []
      headerId: 5
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 10
      paused: false
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:18.525402Z'
    - actionState:
        command: CHECK_QUALITY
        id: 7b25fdfb-4a9e-419d-836c-c4348d9d9fd3
        state: WAITING
        timestamp: '2025-08-19T09:18:17.950441Z'
      batteryState: {}
      errors: []
      headerId: 4
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 10
      paused: false
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:17.950873Z'
    - actionState:
        command: factsheetRequest
        id: SOME_ID
        state: FINISHED
        timestamp: '2025-08-19T09:13:34.250080Z'
      batteryState: {}
      errors: []
      headerId: 3
      orderId: ''
      orderUpdateId: 0
      paused: false
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:13:34.249652Z'
    module: SVR4H76530
    sub_category: State
    template_structure:
      actionState: <string>
      batteryState: '[{}]'
      errors: '[[]]'
      headerId: <string>
      orderId: <string>
      orderUpdateId: '[0, 10]'
      paused: '[False]'
      serialNumber: '[SVR4H76530]'
      timestamp: <datetime>
    validation_rules:
    - serialNumber muss in [SVR4H76530] sein
    - batteryState muss in [{}] sein
    - orderUpdateId muss in [0, 10] sein
    - timestamp muss ISO 8601 Format haben
    - errors muss in [[]] sein
    - paused muss in [False] sein
