metadata:
  category: Node-RED
  description: Node-RED Connection Templates
  icon: 🔗
  last_updated: '2025-08-29'
  sub_category: Connection
  version: 3.0.0
templates:
  module/v1/ff/NodeRed/SVR4H73275/connection:
    category: Node-RED
    description: Node-RED SVR4H73275 Connection
    examples:
    - connectionState: ONLINE
      headerId: 2
      ip: '-1'
      manufacturer: Fischertechnik
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:08:58.660990Z'
      version: 1.6.0+gitc321c85
    - connectionState: ONLINE
      headerId: 2
      ip: '-1'
      manufacturer: Fischertechnik
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:08:58.660990Z'
      version: 1.6.0+gitc321c85
    - connectionState: ONLINE
      headerId: 2
      ip: '-1'
      manufacturer: Fischertechnik
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T07:12:55.735613Z'
      version: 1.6.0+gitc321c85
    - connectionState: ONLINE
      headerId: 2
      ip: '-1'
      manufacturer: Fischertechnik
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T07:12:55.735613Z'
      version: 1.6.0+gitc321c85
    - connectionState: ONLINE
      headerId: 2
      ip: '-1'
      manufacturer: Fischertechnik
      serialNumber: SVR4H73275
      timestamp: '2025-08-25T06:47:13.691731Z'
      version: 1.6.0+gitc321c85
    module: SVR4H73275
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: '[2]'
      ip: '[-1]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[SVR4H73275]'
      timestamp: <datetime>
      version: '[1.6.0+gitc321c85]'
    validation_rules:
    - headerId muss in [2] sein
    - timestamp muss ISO 8601 Format haben
    - version muss in [1.6.0+gitc321c85] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [SVR4H73275] sein
    - connectionState muss in [ONLINE] sein
    - ip muss in [-1] sein
  module/v1/ff/NodeRed/SVR4H76530/connection:
    category: Node-RED
    description: Node-RED SVR4H76530 Connection
    examples:
    - connectionState: ONLINE
      headerId: 2
      manufacturer: Fischertechnik
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T08:52:32.608107Z'
      version: 1.0.0
    - connectionState: ONLINE
      headerId: 2
      manufacturer: Fischertechnik
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T08:52:32.608107Z'
      version: 1.0.0
    - connectionState: ONLINE
      headerId: 2
      manufacturer: Fischertechnik
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T16:21:51.154051Z'
      version: 1.0.0
    - connectionState: ONLINE
      headerId: 2
      manufacturer: Fischertechnik
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T16:21:51.154051Z'
      version: 1.0.0
    - connectionState: ONLINE
      headerId: 2
      manufacturer: Fischertechnik
      serialNumber: SVR4H76530
      timestamp: '2025-08-22T16:12:52.175710Z'
      version: 1.0.0
    module: SVR4H76530
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: '[2]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[SVR4H76530]'
      timestamp: <datetime>
      version: '[1.0.0]'
    validation_rules:
    - headerId muss in [2] sein
    - timestamp muss ISO 8601 Format haben
    - version muss in [1.0.0] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [SVR4H76530] sein
    - connectionState muss in [ONLINE] sein
