metadata:
  category: CCU
  description: Auto-analyzed template for CCU state config
  last_updated: '2025-09-15'
  source: ccu_template_analyzer
  sub_category: State
  version: 0.1.0
templates:
  ccu.state.config:
    category: CCU
    description: Template for CCU state config
    direction: inbound
    examples:
    - ftsSettings:
        chargeThresholdPercent: 10
      productionDurations:
        BLUE: 550
        RED: 560
        WHITE: 580
      productionSettings:
        maxParallelOrders: 4
    structure: {}
    sub_category: State
    validation:
      field_types: {}
      required_fields: []
