metadata:
  category: TXT
  description: Auto-analyzed template for TXT hbw
  last_updated: '2025-09-15'
  source: txt_template_analyzer
  version: 0.1.0
templates:
  txt..f.i.config.hbw:
    category: TXT
    description: Template for TXT hbw
    direction: inbound
    examples:
    - ts: '2025-08-19T09:08:26.191Z'
      warehouses:
      - SVR3QA0022
    - ts: '2025-08-25T06:46:39.746Z'
      warehouses:
      - SVR3QA0022
    - ts: '2025-08-20T07:12:20.229Z'
      warehouses:
      - SVR3QA0022
    structure:
      ts: <datetime>
      warehouses:
      - <moduleId>
    validation:
      field_types: {}
      required_fields: []
