dashboard:
  auto_refresh: true
  language: en
  refresh_interval: 5
  theme: light
modules:
  aiqs:
    enabled: true
    name: AI Quality Station
  dps:
    enabled: true
    name: Drill Processing Station
  drill:
    enabled: true
    name: Bohrstation
  hbw:
    enabled: true
    name: Hochregallager
  mill:
    enabled: true
    name: Frässtation
  mpo:
    enabled: true
    name: Multi-Processing-Outlet
  oven:
    enabled: true
    name: Ofen
  ssc:
    enabled: true
    name: Sorting Station Control
  vgr:
    enabled: true
    name: Vakuum Greifer Roboter
mqtt:
  broker: localhost
  password: ''
  port: 1883
  topics:
    aiqs: aps/aiqs/#
    dps: aps/dps/#
    drill: aps/drill/#
    hbw: aps/hbw/#
    mill: aps/mill/#
    mpo: aps/mpo/#
    oven: aps/oven/#
    ssc: aps/ssc/#
    vgr: aps/vgr/#
  username: ''
nfc:
  enabled: true
  reader_type: default
  timeout: 30
