# OMF Topic-Message Mapping
# Verknüpft MQTT-Topics mit Message-Templates für semantische Nachrichten
# Version: 3.0.0

metadata:
  version: "3.0.0"
  description: "Mapping zwischen MQTT-Topics und Message-Templates"
  last_updated: "2025-08-29"
  author: "OMF Development Team"

# Topic-Message Mappings
topic_mappings:
  # CCU Topics
  "ccu/control":
    template: "ccu/control"
    direction: "outbound"
    description: "CCU-Befehle senden"
    semantic_purpose: "Steuerung der CCU"
    
  "ccu/set/reset":
    template: "ccu/control"
    direction: "outbound"
    description: "CCU-Factory-Reset senden"
    semantic_purpose: "Factory-Reset der Fabrik"
    
  "ccu/state/config":
    template: "ccu/state/config"
    direction: "inbound"
    description: "CCU-Konfigurationsstatus empfangen"
    semantic_purpose: "CCU-Konfiguration überwachen"
    
  "ccu/state/status":
    template: "ccu/state/status"
    direction: "inbound"
    description: "CCU-Status empfangen"
    semantic_purpose: "CCU-Status überwachen"
    
  "ccu/pairing/state":
    template: "ccu/state"
    direction: "inbound"
    description: "Modul-Pairing-Status mit Availability, Connection und IP-Adressen empfangen"
    semantic_purpose: "Modul-Verfügbarkeit und Verbindungsstatus überwachen"

  # Module Topics - Generische Mappings
  "module/v1/ff/{module_id}/connection":
    template: "module/connection"
    direction: "bidirectional"
    description: "Modul-Verbindungsstatus"
    semantic_purpose: "Modul-Verbindung überwachen"
    variable_fields:
      module_id: "<module_serial_number>"
    
  "module/v1/ff/{module_id}/state":
    template: "module/state"
    direction: "bidirectional"
    description: "Modul-Zustand"
    semantic_purpose: "Modul-Zustand überwachen"
    variable_fields:
      module_id: "<module_serial_number>"
    
  "module/v1/ff/{module_id}/order":
    template: "module/order"
    direction: "outbound"
    description: "Modul-Befehle senden"
    semantic_purpose: "Modul steuern"
    variable_fields:
      module_id: "<module_serial_number>"
    
  "module/v1/ff/{module_id}/factsheet":
    template: "module/factsheet"
    direction: "inbound"
    description: "Modul-Konfiguration empfangen"
    semantic_purpose: "Modul-Konfiguration abrufen"
    variable_fields:
      module_id: "<module_serial_number>"

  # HBW (Hochregallager) - Spezifische Topics für Lagerbestand
  "module/v1/ff/SVR3QA0022/state":
    template: "module/state"
    direction: "inbound"
    description: "HBW Lagerbestand Status - Aktuelle Belegung aller 9 Positionen (A1-C3)"
    semantic_purpose: "Lagerbestand überwachen und Dashboard aktualisieren"
    payload_structure:
      loads:
        - loadType: "RED|BLUE|WHITE"
        - loadPosition: "A1|A2|A3|B1|B2|B3|C1|C2|C3"
        - loadId: "unique_identifier"
    update_frequency: "on_change"
    dependencies: ["initial_state", "order_processing"]
    examples:
      initial_state:
        description: "Erste Nachricht mit vollständigem Lagerbestand"
        payload: |
          {
            "loads": [
              {"loadType": "RED", "loadPosition": "A1", "loadId": "red_001"},
              {"loadType": "BLUE", "loadPosition": "A2", "loadId": "blue_001"},
              {"loadType": "WHITE", "loadPosition": "A3", "loadId": "white_001"},
              {"loadType": "RED", "loadPosition": "B1", "loadId": "red_002"},
              {"loadType": "BLUE", "loadPosition": "B2", "loadId": "blue_002"},
              {"loadType": "WHITE", "loadPosition": "B3", "loadId": "white_002"},
              {"loadType": "RED", "loadPosition": "C1", "loadId": "red_003"},
              {"loadType": "BLUE", "loadPosition": "C2", "loadId": "blue_003"},
              {"loadType": "WHITE", "loadPosition": "C3", "loadId": "white_003"}
            ]
          }
      delta_update:
        description: "Folge-Nachrichten mit Änderungen"
        payload: |
          {
            "loads": [
              {"loadType": "RED", "loadPosition": "A1", "loadId": "red_001"},
              {"loadType": "BLUE", "loadPosition": "A2", "loadId": "blue_001"}
            ]
          }
    temporal_dependencies:
      first_message: "Vollständiger Lagerbestand als Basis-Zustand"
      subsequent_messages: "Nur geänderte Positionen (Delta-Updates)"
      timestamp_format: "Unix timestamp (z.B. 1756980963.7231271)"

  "module/v1/ff/SVR3QA0022/order":
    template: "module/order"
    direction: "outbound"
    description: "HBW Bestellungen senden - Werkstück-Einlagerung oder -Auslagerung"
    semantic_purpose: "HBW-Modul steuern für Lagerbestand-Management"
    payload_structure:
      orderType: "STORAGE|RETRIEVAL"
      workpieceType: "RED|BLUE|WHITE"
      quantity: "integer"
      priority: "normal|high|urgent"
      targetPosition: "A1|A2|A3|B1|B2|B3|C1|C2|C3"  # Optional für STORAGE
    examples:
      storage_order:
        description: "Werkstück einlagern"
        payload: |
          {
            "orderType": "STORAGE",
            "workpieceType": "RED",
            "quantity": 1,
            "priority": "normal",
            "targetPosition": "A1"
          }
      retrieval_order:
        description: "Werkstück auslagern"
        payload: |
          {
            "orderType": "RETRIEVAL",
            "workpieceType": "BLUE",
            "quantity": 1,
            "priority": "normal"
          }
    error_handling:
      timeout: "30_seconds"
      retry_attempts: 3
      error_topics: ["module/v1/ff/SVR3QA0022/error"]

  "module/v1/ff/SVR3QA0022/connection":
    template: "module/connection"
    direction: "bidirectional"
    description: "HBW Verbindungsstatus - Verfügbarkeit und Verbindungsqualität"
    semantic_purpose: "HBW-Modul-Verbindung überwachen"
    payload_structure:
      status: "CONNECTED|DISCONNECTED|ERROR"
      availability: "READY|BUSY|ERROR|OFFLINE"
      lastSeen: "ISO_timestamp"
      connectionQuality: "excellent|good|poor|none"

  "module/v1/ff/SVR3QA0022/factsheet":
    template: "module/factsheet"
    direction: "inbound"
    description: "HBW Modul-Informationen - Konfiguration und Fähigkeiten"
    semantic_purpose: "HBW-Modul-Konfiguration abrufen"
    payload_structure:
      moduleId: "SVR3QA0022"
      moduleType: "HBW"
      capabilities: ["STORAGE", "RETRIEVAL", "POSITION_MANAGEMENT"]
      supportedWorkpieceTypes: ["RED", "BLUE", "WHITE"]
      positionCount: 9
      positions: ["A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3"]

  # TXT Topics
  "/j1/txt/1/f/i/order":
    template: "txt/order_input"
    direction: "inbound"
    description: "TXT-Auftragseingang empfangen"
    semantic_purpose: "Auftragseingang überwachen"
    
  "/j1/txt/1/f/i/stock":
    template: "txt/stock_input"
    direction: "inbound"
    description: "TXT-Lagerbestand empfangen"
    semantic_purpose: "Lagerbestand überwachen"
    
  "/j1/txt/1/c/bme680":
    template: "txt/sensor_control"
    direction: "outbound"
    description: "TXT-Sensor-Steuerung senden"
    semantic_purpose: "Sensoren steuern"

  # Node-RED Topics
  "ccu/state/dashboard":
    template: "node_red/dashboard_state"
    direction: "inbound"
    description: "Node-RED Dashboard-Status empfangen"
    semantic_purpose: "Dashboard-Status überwachen"
    
  "module/v1/ff/NodeRed/{module_id}/connection":
    template: "node_red/module_connection"
    direction: "bidirectional"
    description: "Node-RED Modul-Verbindung"
    semantic_purpose: "Node-RED Modul-Verbindung überwachen"
    variable_fields:
      module_id: "<module_serial_number>"

# Template-Kategorien für Dashboard-Gruppierung
template_categories:
  MODULE_CONTROL:
    description: "Modul-Steuerung"
    templates: ["module/order", "module/state", "module/connection"]
    icon: "⚙️"
    
  MODULE_MONITORING:
    description: "Modul-Überwachung"
    templates: ["module/state", "module/connection", "module/factsheet"]
    icon: "📊"
    
  CCU_CONTROL:
    description: "CCU-Steuerung"
    templates: ["ccu/control", "ccu/state/config", "ccu/state/status"]
    icon: "🏭"
    
  TXT_CONTROL:
    description: "TXT-Steuerung"
    templates: ["txt/order_input", "txt/stock_input", "txt/sensor_control"]
    icon: "🎛️"
    
  NODE_RED_MONITORING:
    description: "Node-RED Überwachung"
    templates: ["node_red/dashboard_state", "node_red/module_connection"]
    icon: "🔄"

# Validierungsregeln für Topic-Template Mappings
validation_rules:
  required_fields:
    - "template"
    - "direction"
    - "description"
    - "semantic_purpose"
  
  direction_values:
    - "inbound"
    - "outbound"
    - "bidirectional"
  
  template_patterns:
    - "module/{sub_category}"
    - "ccu/{sub_category}"
    - "txt/{sub_category}"
    - "node_red/{sub_category}"
