metadata:
  category: Node-RED
  description: Node-RED Order Templates
  icon: 📋
  last_updated: '2025-08-29'
  sub_category: Order
  version: 3.0.0
templates:
  module/v1/ff/NodeRed/SVR4H73275/order:
    category: Node-RED
    description: Node-RED SVR4H73275 Order
    examples:
    - action:
        command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755595028336
            - code: 600
              ts: 1755595064912
            - code: 200
              ts: 1755595103032
            state: PROCESSED
            type: RED
            workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 11
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:18:41.187Z'
    - action:
        command: PICK
        id: 7d18d976-8a7d-4e81-9387-afa21020c25e
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755684009575
            - code: 700
              ts: 1755684133967
            - code: 600
              ts: 1755684243218
            - code: 200
              ts: 1755684356607
            - code: 100
              ts: 1755680183643
            - code: 300
              ts: 1755680212526
            state: PROCESSED
            type: BLUE
            workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 18
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T10:06:47.500Z'
    - action:
        command: PICK
        id: fbb6bd63-3eb1-4ef2-8618-f9036d468429
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755683962675
            - code: 700
              ts: 1755684076008
            - code: 600
              ts: 1755684164181
            - code: 200
              ts: 1755684273420
            - code: 100
              ts: 1755680106493
            - code: 300
              ts: 1755680137522
            state: PROCESSED
            type: BLUE
            workpieceId: 048989ca341290
      orderId: b0c9a823-255d-458a-a409-1052cc725aac
      orderUpdateId: 18
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T10:05:56.739Z'
    - action:
        command: PICK
        id: a940bc49-c77d-4269-948e-88e933adeb8e
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755683914567
            - code: 700
              ts: 1755684043123
            - code: 600
              ts: 1755684097304
            - code: 200
              ts: 1755684209410
            - code: 100
              ts: 1755680030880
            - code: 300
              ts: 1755680061499
            state: PROCESSED
            type: BLUE
            workpieceId: 04a189ca341290
      orderId: a73e60cf-a116-4dcf-b2d1-3797b6f96912
      orderUpdateId: 17
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T10:04:58.236Z'
    - action:
        command: PICK
        id: 5692d8a0-bbc4-43a4-8d4f-d86f0c896abf
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755595760241
            - code: 700
              ts: 1755595793651
            - code: 600
              ts: 1755595834892
            - code: 200
              ts: 1755595873063
            state: PROCESSED
            type: BLUE
            workpieceId: 047389ca341291
      orderId: 598cba14-5cb5-43e7-b8cc-530d87d2cfa3
      orderUpdateId: 15
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:31:30.940Z'
    module: SVR4H73275
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: <string>
      serialNumber: '[SVR4H73275]'
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - serialNumber muss in [SVR4H73275] sein
  module/v1/ff/NodeRed/SVR4H76530/order:
    category: Node-RED
    description: Node-RED SVR4H76530 Order
    examples:
    - action:
        command: CHECK_QUALITY
        id: 7b25fdfb-4a9e-419d-836c-c4348d9d9fd3
        metadata:
          type: RED
          workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 10
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:17.885Z'
    - action:
        command: CHECK_QUALITY
        id: 4030fb15-9ffa-449c-b510-dc61b0184e48
        metadata:
          type: BLUE
          workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 10
      serialNumber: SVR4H76530
      timestamp: '2025-08-20T10:05:51.481Z'
    - action:
        command: CHECK_QUALITY
        id: a9219dcc-3bcf-4bea-8ff7-fc1ecbd2c4b2
        metadata:
          type: BLUE
          workpieceId: 048989ca341290
      orderId: b0c9a823-255d-458a-a409-1052cc725aac
      orderUpdateId: 10
      serialNumber: SVR4H76530
      timestamp: '2025-08-20T10:04:27.508Z'
    - action:
        command: CHECK_QUALITY
        id: b3e38b70-9956-40ca-8b6d-9db29fefccef
        metadata:
          type: BLUE
          workpieceId: 04a189ca341290
      orderId: a73e60cf-a116-4dcf-b2d1-3797b6f96912
      orderUpdateId: 10
      serialNumber: SVR4H76530
      timestamp: '2025-08-20T10:03:24.480Z'
    - action:
        command: CHECK_QUALITY
        id: 0656dfd4-54e9-4eb9-876d-1fbf1bb6f7b5
        metadata:
          type: BLUE
          workpieceId: 047389ca341291
      orderId: 598cba14-5cb5-43e7-b8cc-530d87d2cfa3
      orderUpdateId: 10
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:31:07.911Z'
    module: SVR4H76530
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: '[10]'
      serialNumber: '[SVR4H76530]'
      timestamp: <datetime>
    validation_rules:
    - serialNumber muss in [SVR4H76530] sein
    - orderUpdateId muss in [10] sein
    - timestamp muss ISO 8601 Format haben
