# DSP-Edge VE 192.168.0.201 — live ingest (no local SQL Server container)
# Copy to .env on the VE:  cp env.dsp .env

MSSQL_HOST=host.docker.internal
MSSQL_PORT=1433
MSSQL_DB=osf_edge
MSSQL_USER=osf_edge
MSSQL_PASSWORD=OsfEdge_App9#
MSSQL_ENCRYPT=false
MSSQL_TRUST_SERVER_CERTIFICATE=true
MSSQL_GRAFANA_URL=host.docker.internal:1433

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=admin
GRAFANA_EXTERNAL_PORT=3000
QUERY_API_EXTERNAL_PORT=3081

MQTT_HOST=192.168.0.100
MQTT_PORT=1883
MQTT_USERNAME=default
MQTT_PASSWORD=default
MQTT_CLIENT_ID=osf-persistence-dsp-201

PERSISTENCE_MODE=live
RAW_RETENTION_DAYS=14
SENSOR_INTERVAL_SECONDS=5
SENSOR_IDLE_INTERVAL_SECONDS=60
ENABLE_RAW_MESSAGES=true
ENABLE_CAMERA_TOPIC=false
LOG_LEVEL=info
