metadata:
  category: TXT
  description: Semantic Txt Templates
  generated: true
  last_updated: '2025-08-29'
  semantic: true
  version: 3.0.0
templates:
  txt/order_input:
    category: TXT
    description: TXT Order Input - Generisch
    mqtt_control_usage:
      description: Auftragszustand über TXT-Controller abfragen
      example_payload:
        state: WAITING_FOR_ORDER
        ts: '2025-08-29T10:00:00Z'
        type: RED
      example_topic: /j1/txt/1/f/i/order
    mqtt_topic_pattern: /j1/txt/1/f/i/order
    semantic_purpose: Auftragseingang über TXT-Controller
    template_structure:
      state: <order_state>
      ts: <datetime>
      type: <workpiece_type>
    validation_rules:
    - ts muss ISO 8601 Format haben
    - state muss gültiger Auftragszustand sein
    - type muss gültiger Werkstück-Typ sein
    variable_fields:
      state:
        description: Zustand des Auftrags
        type: enum
        values:
        - WAITING_FOR_ORDER
        - IN_PROCESS
        - COMPLETED
        - FINISHED
        - RAW
        - RESERVED
      type:
        description: Typ des Werkstücks
        type: enum
        values:
        - RED
        - WHITE
        - BLUE
