metadata:
  category: NODE_RED
  description: Semantic Node_Red Templates
  generated: true
  last_updated: '2025-08-29'
  semantic: true
  version: 3.0.0
templates:
  node_red/dashboard_state:
    category: Node-RED
    description: Node-RED Dashboard State - Generisch
    mqtt_control_usage:
      description: Dashboard-Status von Node-RED abfragen
      example_payload:
        active_flows: 3
        flows: 5
        status: running
        timestamp: '2025-08-29T10:00:00Z'
      example_topic: ccu/state/dashboard
    mqtt_topic_pattern: ccu/state/dashboard
    semantic_purpose: Dashboard-Status von Node-RED abfragen
    template_structure:
      active_flows: <active_flows_count>
      flows: <number_of_flows>
      status: <dashboard_status>
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - status muss gültiger Dashboard-Status sein
    - flows muss positive Zahl sein
    - active_flows muss positive Zahl sein
    variable_fields:
      active_flows:
        description: Anzahl aktiver Flows
        type: number
      flows:
        description: Anzahl aller Flows
        type: number
      status:
        description: Status des Dashboards
        type: enum
        values:
        - running
        - stopped
        - error
        - maintenance
