apiVersion: 1

datasources:
  - name: OSF Timescale
    type: grafana-postgresql-datasource
    access: proxy
    isDefault: true
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    jsonData:
      database: ${POSTGRES_DB}
      postgresVersion: 1600
      sslmode: disable
      timescaledb: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
