metadata:
  category: FTS
  description: FTS Factsheet Templates
  icon: 📄
  last_updated: '2025-01-19'
  sub_category: Factsheet
  version: 1.0.0

templates:
  fts/v1/ff/5iO4/factsheet:
    category: FTS
    description: FTS Factsheet Information
    examples:
    - serialNumber: "5iO4"
      model: "FTS-AGV-001"
      manufacturer: "FTS Manufacturer"
      version: "1.1.0+git250d287"
      firmware: "1.0.5"
      hardware: "v2.1"
      capabilities:
        - "navigation"
        - "load_handling"
        - "battery_management"
      specifications:
        maxSpeed: 1.5
        maxLoad: 50
        batteryCapacity: 100
        dimensions:
          length: 1200
          width: 800
          height: 400
      loadHandling:
        loadSets:
          - setName: "Standard Load"
            loadType: "PALLET"
            loadDimensions:
              length: 600
              width: 400
              height: 200
      protocolFeatures:
        agvActions:
          - actionType: "DOCK"
            actionScopes: "MODULE"
          - actionType: "TURN"
            actionScopes: "INTERSECTION"
          - actionType: "PASS"
            actionScopes: "INTERSECTION"
    - serialNumber: "5iO4"
      model: "FTS-AGV-002"
      manufacturer: "FTS Manufacturer"
      version: "1.2.0+git300a456"
      firmware: "1.1.0"
      hardware: "v2.2"
      capabilities:
        - "navigation"
        - "load_handling"
        - "battery_management"
        - "advanced_sensors"
      specifications:
        maxSpeed: 2.0
        maxLoad: 75
        batteryCapacity: 120
        dimensions:
          length: 1400
          width: 900
          height: 450
      loadHandling:
        loadSets:
          - setName: "Heavy Load"
            loadType: "HEAVY_PALLET"
            loadDimensions:
              length: 800
              width: 600
              height: 300
      protocolFeatures:
        agvActions:
          - actionType: "DOCK"
            actionScopes: "MODULE"
          - actionType: "TURN"
            actionScopes: "INTERSECTION"
          - actionType: "PASS"
            actionScopes: "INTERSECTION"
          - actionType: "LIFT"
            actionScopes: "LOAD_POSITION"
    module: FTS
    sub_category: Factsheet
    template_structure:
      serialNumber: <string>
      model: <string>
      manufacturer: <string>
      version: <string>
      firmware: <string>
      hardware: <string>
      capabilities: <array>
      specifications:
        maxSpeed: <number>
        maxLoad: <number>
        batteryCapacity: <number>
        dimensions:
          length: <number>
          width: <number>
          height: <number>
      loadHandling:
        loadSets: <array>
      protocolFeatures:
        agvActions: <array>
    validation_rules:
    - serialNumber muss String sein
    - model muss String sein
    - manufacturer muss String sein
    - version muss String sein
    - firmware muss String sein
    - hardware muss String sein
    - capabilities muss Array sein
    - maxSpeed muss positive Number sein
    - maxLoad muss positive Number sein
    - batteryCapacity muss positive Number sein
    - dimensions müssen positive Numbers sein
    - loadSets muss Array sein
    - agvActions muss Array sein
