metadata:
  category: FTS
  description: FTS InstantAction Templates
  icon: ⚡
  last_updated: '2025-01-19'
  sub_category: InstantAction
  version: 1.0.0

templates:
  fts/v1/ff/5iO4/instantAction:
    category: FTS
    description: FTS InstantAction Commands
    examples:
    - serialNumber: "5iO4"
      timestamp: "2025-08-19T09:18:14.861Z"
      actions:
        - actionId: "d055f1e7-8e60-4b97-aca8-bf0802cb4d93"
          actionType: "clearLoadHandler"
          metadata:
            loadDropped: true
            loadType: "RED"
            loadId: "040a8dca341291"
            loadPosition: "1"
    - serialNumber: "5iO4"
      timestamp: "2025-08-19T09:17:30.500Z"
      actions:
        - actionId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
          actionType: "getStatus"
          metadata: {}
    - serialNumber: "5iO4"
      timestamp: "2025-08-19T09:16:45.200Z"
      actions:
        - actionId: "b2c3d4e5-f6g7-8901-bcde-f23456789012"
          actionType: "reset"
          metadata:
            resetType: "SOFT"
            reason: "user_request"
    - serialNumber: "5iO4"
      timestamp: "2025-08-19T09:15:20.100Z"
      actions:
        - actionId: "c3d4e5f6-g7h8-9012-cdef-345678901234"
          actionType: "findInitialDockPosition"
          metadata:
            searchRadius: 5.0
            preferredModule: "SVR3QA0022"
    - serialNumber: "5iO4"
      timestamp: "2025-08-19T09:14:10.800Z"
      actions:
        - actionId: "d4e5f6g7-h8i9-0123-defg-456789012345"
          actionType: "clearLoadHandler"
          metadata:
            loadDropped: false
            loadType: "BLUE"
            loadId: "04798eca341290"
            loadPosition: "2"
    module: FTS
    sub_category: InstantAction
    template_structure:
      serialNumber: <string>
      timestamp: <datetime>
      actions:
        - actionId: <string>
          actionType: <string>
          metadata: <object>
    validation_rules:
    - serialNumber muss String sein
    - timestamp muss ISO 8601 Format haben
    - actions muss Array sein
    - actionId muss String sein (UUID Format)
    - actionType muss in [clearLoadHandler, getStatus, reset, findInitialDockPosition, pause, resume] sein
    - metadata muss Object sein
    - loadDropped muss Boolean sein (falls vorhanden)
    - loadType muss in [RED, BLUE, WHITE, RAW] sein (falls vorhanden)
    - loadId muss String sein (falls vorhanden)
    - loadPosition muss String sein (falls vorhanden)
    - resetType muss in [SOFT, HARD] sein (falls vorhanden)
    - searchRadius muss positive Number sein (falls vorhanden)
    - preferredModule muss String sein (falls vorhanden)
