# OMF FTS Navigation Template
# Template für FTS-Navigations-Messages
# Version: 3.3.0

metadata:
  category: "FTS"
  sub_category: "Navigation"
  version: "3.3.0"
  last_updated: "2025-09-09"
  author: "OMF Development Team"

templates:
  "fts/navigation":
    name: "fts/navigation"
    description: "FTS-Navigations-Message für Routenplanung"
    version: "3.3.0"

# MQTT-Konfiguration
mqtt:
  topic_pattern: "fts/v1/ff/{fts_serial}/order"
  direction: "outbound"
  qos: 1
  retain: false

# Message-Struktur
structure:
  required_fields:
    - "timestamp"
    - "orderId"
    - "orderUpdateId"
    - "nodes"
    - "edges"
    - "serialNumber"
  
  optional_fields:
    - "metadata"
    - "priority"
    - "timeout"
  
  field_definitions:
    timestamp:
      type: "string"
      format: "ISO 8601"
      description: "Zeitstempel der Message-Generierung"
      example: "2025-09-09T13:06:18.917370Z"
    
    orderId:
      type: "string"
      format: "UUID oder benutzerdefiniert"
      description: "Eindeutige Order-ID für die Navigation"
      example: "test-navigation-dps-to-hbw-wareneingang-001"
    
    orderUpdateId:
      type: "integer"
      description: "Sequenzielle Update-ID für die Order"
      example: 0
    
    serialNumber:
      type: "string"
      description: "FTS Serial Number"
      example: "5iO4"
    
    nodes:
      type: "array"
      description: "Array von Navigations-Knoten"
      structure:
        - "id: string (Knoten-ID)"
        - "linkedEdges: array (verbundene Edges)"
        - "action: object (optional, für Kreuzungspunkte)"
    
    edges:
      type: "array"
      description: "Array von Navigations-Edges"
      structure:
        - "id: string (Edge-ID)"
        - "length: number (Länge in cm)"
        - "linkedNodes: array (verbundene Knoten)"

# Validierungsregeln
validation_rules:
  - "timestamp muss ISO 8601 Format haben"
  - "orderId muss String sein"
  - "orderUpdateId muss Integer sein"
  - "serialNumber muss '5iO4' sein"
  - "nodes muss Array mit mindestens 2 Elementen sein"
  - "edges muss Array mit mindestens 1 Element sein"
  - "Jeder Node muss 'id' und 'linkedEdges' haben"
  - "Jede Edge muss 'id', 'length' und 'linkedNodes' haben"

# Variable Felder
variable_fields:
  fts_serial:
    type: "enum"
    values: ["5iO4"]
    description: "FTS Serial Number"
  
  orderId:
    type: "custom"
    description: "Benutzerdefinierte Order-ID"
    pattern: "alphanumeric-with-dashes"
  
  orderUpdateId:
    type: "integer"
    min: 0
    max: 999999
    description: "Sequenzielle Update-ID"

# Beispiel-Message
example_message:
  timestamp: "2025-09-09T13:06:18.917370Z"
  orderId: "test-navigation-dps-to-hbw-wareneingang-001"
  orderUpdateId: 0
  nodes:
    - id: "SVR4H73275"
      linkedEdges: ["SVR4H73275-2"]
    - id: "2"
      linkedEdges: ["SVR4H73275-2", "2-1"]
      action:
        id: "pass-through-2-001"
        type: "PASS"
    - id: "1"
      linkedEdges: ["2-1", "1-SVR3QA0022"]
      action:
        id: "pass-through-1-001"
        type: "PASS"
    - id: "SVR3QA0022"
      linkedEdges: ["1-SVR3QA0022"]
      action:
        type: "DOCK"
        id: "dock-at-hbw-wareneingang-001"
        metadata:
          loadId: "04798eca341290"
          loadType: "WHITE"
          loadPosition: "1"
  edges:
    - id: "SVR4H73275-2"
      length: 380
      linkedNodes: ["SVR4H73275", "2"]
    - id: "2-1"
      length: 360
      linkedNodes: ["2", "1"]
    - id: "1-SVR3QA0022"
      length: 380
      linkedNodes: ["1", "SVR3QA0022"]
  serialNumber: "5iO4"

# Integration
integration:
  route_generator: "FTSRouteGenerator"
  validation: "MessageGenerator.validate_message"
  dashboard_component: "shopfloor_routes"
  test_coverage: "test_fts_route_generator.py"
