# 🔐 Orbis Modellfabrik - Credentials Configuration
# Copy this file to credentials.yml and fill in your actual credentials
# NEVER commit credentials.yml to version control!

# APS Modellfabrik Network Configuration
network:
  ccu_ip: "192.168.0.100"
  mqtt_port: 1883
  network_range: "192.168.0.0/24"
  gateway: "192.168.0.1"
  dns: "192.168.0.1"
  description: "APS Modellfabrik Netzwerk-Konfiguration"

# CCU (Central Control Unit) Access
ccu:
  component: "CCU (Central Control Unit)"
  hardware: "Raspberry Pi"
  hostname: "192.168.0.100"
  ssh:
    username: "ff22"
    password: "ff22+"  # Change this!
    port: 22
    enabled: true
  description: "Zentrale Steuereinheit der APS-Modellfabrik"

# -----------------------------------------------------------------------------
# MQTT Broker Configuration
# -----------------------------------------------------------------------------
# Configuration for MQTT brokers used in the project.
# You can define multiple brokers and select one in the dashboard.
mqtt_brokers:
  - name: "Modellfabrik-Labor"
    host: "192.168.0.100"
    port: 1883
    username: "default"
    password: "default"
  - name: "Entwicklungs-Broker"
    host: "localhost"
    port: 1883
    username: "dev"
    password: "dev"

# Node-RED Dashboard
node_red:
  component: "Node-RED"
  software: "Gateway MQTT und OPC-UA"
  host: "192.168.0.100"
  port: 1880
  ssl: false
  username: ""  # Keine Authentifizierung
  password: ""  # Keine Authentifizierung
  enabled: true
  description: "Web-basiertes Dashboard für MQTT und OPC-UA Gateway"

# Router TL (TP-Link)
router:
  component: "Router TL"
  software: "Konfiguration Netzwerk"
  host: "192.168.0.1"
  alternative_url: "http://tplinkap.net"
  username: "admin"
  password: "admin1"  # Change this!
  enabled: true
  description: "Netzwerk-Router für APS-Modellfabrik"

# TXT 4.0 Controller
txt4_controller:
  component: "TXT 4.0 Controller"
  software: "Fischertechnik TXT 4.0"
  ssh:
    host: "192.168.0.x"  # Replace with actual IP
    port: 22
    username: "ft"
    password: "fischertechnik"  # Change this!
    enabled: true
  web:
    host: "192.168.0.x"  # Replace with actual IP
    port: 80
    username: "ft"
    password: "fischertechnik"  # Change this!
    enabled: true
  description: "Fischertechnik TXT 4.0 Controller"

# SPS Siemens S7-1200
sps_siemens:
  component: "SPS Siemens S7-1200"
  software: "OPC-UA"
  port: 4840
  authentication: false  # OPC-UA Standard
  modules:
    mill:
      ip_range: "192.168.0.40-45"
      description: "MILL Modul"
    drill:
      ip_range: "192.168.0.50-55"
      description: "DRILL Modul"
    oven:
      ip_range: "192.168.0.60-65"
      description: "OVEN Modul"
    aiqs:
      ip_range: "192.168.0.70-75"
      description: "AIQS Modul"
    hbw:
      ip_range: "192.168.0.80-83"
      description: "HBW Modul"
    dps:
      ip_range: "192.168.0.90"
      description: "DPS Modul"
  description: "Siemens S7-1200 SPS mit OPC-UA Protokoll"

# Web Interfaces
web_interfaces:
  main:
    url: "http://192.168.0.100:80"
    username: ""
    password: ""
    enabled: false
  
  alternative:
    url: "http://192.168.0.100:8080"
    username: ""
    password: ""
    enabled: false

# Development Environment
development:
  local_mqtt:
    host: "localhost"
    port: 1883
    authentication: false
  
  python_venv:
    path: "/Users/oliver/Projects/ORBIS-Modellfabrik/.venv"
    activation: "source .venv/bin/activate"

# Security Settings
security:
  change_default_passwords: true
  enable_firewall: true
  restrict_ssh_access: true
  use_ssl: false  # Enable for production

# Logging Configuration
logging:
  level: "INFO"
  file: "orbis_access.log"
  max_size: "10MB"
  backup_count: 5

# Backup Configuration
backup:
  enabled: true
  frequency: "daily"
  retention_days: 30
  include_configs: true
  include_logs: true

# Contact Information
contacts:
  system_admin: ""
  network_admin: ""
  orbis_team: ""
  emergency_contact: ""

# Notes and Status
status:
  last_updated: "2025-08-14"
  version: "1.0"
  tested: false
  production_ready: false
  notes: "Credentials need to be discovered and tested"
