metadata:
  category: TXT
  description: TXT Order Input Message Template
  template_type: "message_structure_definition"
  last_updated: "2025-08-29"
  version: 3.0.0

# TEMPLATE: Message-Struktur-Definition
template:
  name: "txt/order_input"
  description: "TXT Order Input - Message Structure Definition"
  semantic_purpose: "Auftragseingang über TXT-Controller"
  
  # SYNTAX: Struktur der Nachricht
  structure:
    required_fields:
      - state
      - ts
    optional_fields:
      - type
      - details
    
    field_definitions:
      state:
        type: "string"
        pattern: "enum"
        description: "Zustand des Auftrags"
        validation: "must be valid order state"
        
      type:
        type: "string"
        pattern: "enum"
        description: "Typ des Werkstücks"
        validation: "must be valid workpiece type"
        
      details:
        type: "object"
        description: "Zusätzliche Auftragsdetails"
        validation: "optional object with additional information"
        
      ts:
        type: "string"
        pattern: "iso8601"
        description: "Zeitstempel"
        validation: "must be ISO 8601 format"
  
  # SEMANTICS: Validierungsregeln
  validation_rules:
    - "ts muss ISO 8601 Format haben"
    - "state muss gültiger Auftragszustand sein"
    - "type ist optional (RED, WHITE, BLUE)"
    - "details ist optional"
  
  # VARIABLE FIELDS: Enum-Werte für Generierung
  variable_fields:
    state:
      type: "enum"
      values: ["WAITING_FOR_ORDER", "IN_PROCESS", "COMPLETED", "FINISHED", "RAW", "RESERVED"]
      description: "Zustand des Auftrags"
      
    type:
      type: "enum"
      values: ["RED", "WHITE", "BLUE"]
      description: "Typ des Werkstücks"
  
  # MQTT INTEGRATION
  mqtt:
    topic_pattern: "/j1/txt/1/f/i/order"
    direction: "inbound"
    qos: 1
    retain: false
    
  # USAGE EXAMPLES (mehrere Beispiele für ENUM-Werte)
  usage_examples:
    - description: "Wartend auf Auftrag (WAITING_FOR_ORDER)"
      topic: "/j1/txt/1/f/i/order"
      payload:
        state: "WAITING_FOR_ORDER"
        ts: "2025-08-29T10:00:00Z"
        
    - description: "Auftrag in Bearbeitung (IN_PROCESS) - Rotes Werkstück"
      topic: "/j1/txt/1/f/i/order"
      payload:
        state: "IN_PROCESS"
        type: "RED"
        details:
          workpiece_id: "RED_001"
          position: "A1"
        ts: "2025-08-29T10:05:00Z"
        
    - description: "Auftrag abgeschlossen (COMPLETED) - Weißes Werkstück"
      topic: "/j1/txt/1/f/i/order"
      payload:
        state: "COMPLETED"
        type: "WHITE"
        details:
          workpiece_id: "WHITE_001"
          quality_score: 95
        ts: "2025-08-29T10:10:00Z"
        
    - description: "Auftrag fertiggestellt (FINISHED) - Blaues Werkstück"
      topic: "/j1/txt/1/f/i/order"
      payload:
        state: "FINISHED"
        type: "BLUE"
        details:
          workpiece_id: "BLUE_001"
          completion_time: "2025-08-29T10:15:00Z"
        ts: "2025-08-29T10:15:00Z"
        
    - description: "Rohmaterial (RAW)"
      topic: "/j1/txt/1/f/i/order"
      payload:
        state: "RAW"
        details:
          material_type: "aluminum"
          dimensions: "100x50x25"
        ts: "2025-08-29T10:20:00Z"
        
    - description: "Auftrag reserviert (RESERVED)"
      topic: "/j1/txt/1/f/i/order"
      payload:
        state: "RESERVED"
        type: "RED"
        details:
          reservation_id: "RES_001"
          reserved_until: "2025-08-29T11:00:00Z"
        ts: "2025-08-29T10:25:00Z"
