metadata:
  category: TXT
  description: TXT Sensor Control Templates
  generated: false
  icon: "🔧"
  last_updated: "2025-08-29"
  sub_category: Control
  version: 3.0.0

templates:
  txt/sensor_control:
    category: TXT
    description: TXT Sensor Control - Generisch
    semantic_purpose: Sensoren über TXT-Controller steuern
    mqtt_topic_pattern: "/j1/txt/1/c/{sensor_type}"
    template_structure:
      sensor_type: "<sensor_type>"
      period: "<number>"
      enabled: "<boolean>"
      ts: "<datetime>"
    variable_fields:
      sensor_type:
        type: enum
        description: "Sensor-Typ"
        values: ["bme680", "cam", "ldr", "ultrasonic"]
      period:
        type: number
        description: "Messintervall in Sekunden"
      enabled:
        type: boolean
        description: "Sensor aktiviert"
      ts:
        type: datetime
        description: "Timestamp"
    validation_rules:
      - ts muss ISO 8601 Format haben
      - period muss positive Zahl sein
      - enabled muss boolean sein
      - sensor_type muss gültiger Sensor-Typ sein
    mqtt_control_usage:
      description: Sensor über TXT-Controller steuern
      example_topic: "/j1/txt/1/c/bme680"
      example_payload:
        sensor_type: "bme680"
        period: 60
        enabled: true
        ts: "2025-08-29T10:00:00Z"
