metadata:
  category: TXT
  description: TXT Stock Input Message Template
  template_type: "message_structure_definition"
  last_updated: "2025-08-29"
  version: 3.0.0

# TEMPLATE: Message-Struktur-Definition
template:
  name: "txt/stock_input"
  description: "TXT Stock Input - Message Structure Definition"
  semantic_purpose: "Lagerbestand über TXT-Controller abrufen"
  
  # SYNTAX: Struktur der Nachricht
  structure:
    required_fields:
      - stock_items
      - ts
    optional_fields:
      - location
      - status
    
    field_definitions:
      stock_items:
        type: "array"
        description: "Liste der Lagerbestände"
        validation: "array of stock item objects"
        
      location:
        type: "string"
        pattern: "enum"
        description: "Lagerstandort"
        validation: "must be valid location"
        
      status:
        type: "string"
        pattern: "enum"
        description: "Lagerstatus"
        validation: "must be valid status"
        
      ts:
        type: "string"
        pattern: "iso8601"
        description: "Zeitstempel"
        validation: "must be ISO 8601 format"
  
  # SEMANTICS: Validierungsregeln
  validation_rules:
    - "ts muss ISO 8601 Format haben"
    - "stock_items muss Array von Lagerbestand-Objekten sein"
    - "location ist optional"
    - "status ist optional"
  
  # VARIABLE FIELDS: Enum-Werte für Generierung
  variable_fields:
    location:
      type: "enum"
      values: ["A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3"]
      description: "Lagerstandort"
      
    status:
      type: "enum"
      values: ["AVAILABLE", "RESERVED", "EMPTY", "MAINTENANCE"]
      description: "Lagerstatus"
  
  # MQTT INTEGRATION
  mqtt:
    topic_pattern: "/j1/txt/1/f/i/stock"
    direction: "inbound"
    qos: 1
    retain: false
    
  # USAGE EXAMPLES (mehrere Beispiele für ENUM-Werte)
  usage_examples:
    - description: "Verfügbarer Lagerbestand (AVAILABLE)"
      topic: "/j1/txt/1/f/i/stock"
      payload:
        stock_items: [
          {
            "position": "A1",
            "workpiece_type": "RED",
            "quantity": 5,
            "status": "AVAILABLE"
          },
          {
            "position": "B2",
            "workpiece_type": "WHITE",
            "quantity": 3,
            "status": "AVAILABLE"
          }
        ]
        location: "A1"
        status: "AVAILABLE"
        ts: "2025-08-29T10:00:00Z"
        
    - description: "Reservierter Lagerbestand (RESERVED)"
      topic: "/j1/txt/1/f/i/stock"
      payload:
        stock_items: [
          {
            "position": "C1",
            "workpiece_type": "BLUE",
            "quantity": 2,
            "status": "RESERVED"
          }
        ]
        location: "C1"
        status: "RESERVED"
        ts: "2025-08-29T10:05:00Z"
        
    - description: "Leerer Lagerbestand (EMPTY)"
      topic: "/j1/txt/1/f/i/stock"
      payload:
        stock_items: []
        location: "A2"
        status: "EMPTY"
        ts: "2025-08-29T10:10:00Z"
        
    - description: "Wartungsmodus (MAINTENANCE)"
      topic: "/j1/txt/1/f/i/stock"
      payload:
        stock_items: [
          {
            "position": "B3",
            "workpiece_type": "RED",
            "quantity": 0,
            "status": "MAINTENANCE"
          }
        ]
        location: "B3"
        status: "MAINTENANCE"
        ts: "2025-08-29T10:15:00Z"
