metadata:
  category: TXT
  description: TXT Function Output Templates
  icon: 🔌
  last_updated: '2025-08-29'
  sub_category: Function Output
  version: 3.0.0
templates:
  /j1/txt/1/o/broadcast:
    category: TXT
    description: TXT Controller /j1/txt/1/o/broadcast
    examples:
    - message: keep-alive
      ts: '2025-08-19T09:16:24.074Z'
    - message: keep-alive
      ts: '2025-08-19T09:16:24.075Z'
    - message: keep-alive
      ts: '2025-08-19T09:17:24.071Z'
    - message: keep-alive
      ts: '2025-08-19T09:17:24.074Z'
    - message: keep-alive
      ts: '2025-08-19T09:18:24.070Z'
    sub_category: Function Output
    template_structure:
      message: '[keep-alive]'
      ts: <datetime>
    validation_rules:
    - ts muss ISO 8601 Format haben
    - message muss in [keep-alive] sein
