metadata:
  category: TXT
  description: TXT Input Templates
  icon: 📥
  last_updated: '2025-08-29'
  sub_category: Input
  version: 3.0.0
templates:
  /j1/txt/1/f/i/config/hbw:
    category: TXT
    description: TXT Controller /j1/txt/1/f/i/config/hbw
    examples:
    - ts: '2025-08-19T09:08:26.191Z'
      warehouses:
      - SVR3QA0022
    - ts: '2025-08-20T07:12:20.229Z'
      warehouses:
      - SVR3QA0022
    - ts: '2025-08-25T06:46:39.746Z'
      warehouses:
      - SVR3QA0022
    - ts: '2025-08-19T07:04:57.566Z'
      warehouses:
      - SVR3QA0022
    - ts: '2025-08-26T06:07:08.450Z'
      warehouses:
      - SVR3QA0022
    sub_category: Input
    template_structure:
      ts: <datetime>
      warehouses:
      - <moduleId>
    validation_rules:
    - ts muss ISO 8601 Format haben
  /j1/txt/1/f/i/order:
    category: TXT
    description: TXT Controller /j1/txt/1/f/i/order
    examples:
    - state: WAITING_FOR_ORDER
      ts: '2025-08-19T09:13:09.366Z'
    - state: IN_PROCESS
      ts: '2025-08-19T09:16:14.679Z'
      type: RED
    - state: IN_PROCESS
      ts: '2025-08-19T09:16:26.708Z'
      type: RED
    - state: IN_PROCESS
      ts: '2025-08-19T09:17:08.360Z'
      type: RED
    - state: IN_PROCESS
      ts: '2025-08-19T09:17:25.212Z'
      type: RED
    sub_category: Input
    template_structure:
      state: '[COMPLETED, FINISHED, IN_PROCESS, RAW, RESERVED, WAITING_FOR_ORDER]'
      ts: <datetime>
    validation_rules:
    - ts muss ISO 8601 Format haben
    - state muss in [COMPLETED, FINISHED, IN_PROCESS, RAW, RESERVED, WAITING_FOR_ORDER]
      sein
  /j1/txt/1/f/i/stock:
    category: TXT
    description: TXT Controller /j1/txt/1/f/i/stock
    examples:
    - stockItems:
      - hbw: SVR3QA0022
        location: A3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: B3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: C3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: A1
        workpiece:
          id: 040a8dca341291
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: B1
        workpiece:
          id: 04798eca341290
          state: RAW
          type: WHITE
      - hbw: SVR3QA0022
        location: C1
        workpiece:
          id: 047389ca341291
          state: RAW
          type: BLUE
      - hbw: SVR3QA0022
        location: A2
        workpiece:
          id: 047f8cca341290
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: B2
        workpiece:
          id: 04808dca341291
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: C2
        workpiece:
          id: 04ab8bca341290
          state: RAW
          type: WHITE
      ts: '2025-08-19T09:13:34.583Z'
    - stockItems:
      - hbw: SVR3QA0022
        location: A3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: B3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: C3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: A1
        workpiece:
          id: 040a8dca341291
          state: RESERVED
          type: RED
      - hbw: SVR3QA0022
        location: B1
        workpiece:
          id: 04798eca341290
          state: RAW
          type: WHITE
      - hbw: SVR3QA0022
        location: C1
        workpiece:
          id: 047389ca341291
          state: RAW
          type: BLUE
      - hbw: SVR3QA0022
        location: A2
        workpiece:
          id: 047f8cca341290
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: B2
        workpiece:
          id: 04808dca341291
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: C2
        workpiece:
          id: 04ab8bca341290
          state: RAW
          type: WHITE
      ts: '2025-08-19T09:16:14.686Z'
    - stockItems:
      - hbw: SVR3QA0022
        location: A3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: B3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: C3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: A1
        workpiece:
          id: 040a8dca341291
          state: RESERVED
          type: RED
      - hbw: SVR3QA0022
        location: B1
        workpiece:
          id: 04798eca341290
          state: RAW
          type: WHITE
      - hbw: SVR3QA0022
        location: C1
        workpiece:
          id: 047389ca341291
          state: RAW
          type: BLUE
      - hbw: SVR3QA0022
        location: A2
        workpiece:
          id: 047f8cca341290
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: B2
        workpiece:
          id: 04808dca341291
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: C2
        workpiece:
          id: 04ab8bca341290
          state: RAW
          type: WHITE
      ts: '2025-08-19T09:16:26.880Z'
    - stockItems:
      - hbw: SVR3QA0022
        location: A3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: B3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: C3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: A1
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: B1
        workpiece:
          id: 04798eca341290
          state: RAW
          type: WHITE
      - hbw: SVR3QA0022
        location: C1
        workpiece:
          id: 047389ca341291
          state: RAW
          type: BLUE
      - hbw: SVR3QA0022
        location: A2
        workpiece:
          id: 047f8cca341290
          state: RESERVED
          type: RED
      - hbw: SVR3QA0022
        location: B2
        workpiece:
          id: 04808dca341291
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: C2
        workpiece:
          id: 04ab8bca341290
          state: RAW
          type: WHITE
      ts: '2025-08-19T09:17:08.322Z'
    - stockItems:
      - hbw: SVR3QA0022
        location: A3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: B3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: C3
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: A1
        workpiece:
          id: ''
          state: RAW
          type: ''
      - hbw: SVR3QA0022
        location: B1
        workpiece:
          id: 04798eca341290
          state: RAW
          type: WHITE
      - hbw: SVR3QA0022
        location: C1
        workpiece:
          id: 047389ca341291
          state: RAW
          type: BLUE
      - hbw: SVR3QA0022
        location: A2
        workpiece:
          id: 047f8cca341290
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: B2
        workpiece:
          id: 04808dca341291
          state: RAW
          type: RED
      - hbw: SVR3QA0022
        location: C2
        workpiece:
          id: 04ab8bca341290
          state: RAW
          type: WHITE
      ts: '2025-08-19T09:17:08.337Z'
    sub_category: Input
    template_structure:
      stockItems:
      - hbw: <string>
        location: <string>
        workpiece: <string>
      ts: <datetime>
    validation_rules:
    - ts muss ISO 8601 Format haben
