metadata:
  category: TXT
  description: TXT Output Templates
  icon: 📤
  last_updated: '2025-08-29'
  sub_category: Output
  version: 3.0.0
templates:
  /j1/txt/1/f/o/order:
    category: TXT
    description: TXT Controller /j1/txt/1/f/o/order
    examples:
    - ts: '2025-08-19T09:16:14.336Z'
      type: RED
    - ts: '2025-08-20T09:57:51.319Z'
      type: BLUE
    - ts: '2025-08-19T09:22:49.486Z'
      type: WHITE
    - ts: '2025-08-20T09:57:56.397Z'
      type: BLUE
    - ts: '2025-08-20T09:57:58.214Z'
      type: BLUE
    sub_category: Output
    template_structure:
      ts: <datetime>
      type: '[BLUE, RED, WHITE]'
    validation_rules:
    - type muss in [BLUE, RED, WHITE] sein
    - ts muss ISO 8601 Format haben
