# OMF Shopfloor Layout Configuration
# 4x3 Grid Layout für Modul-Positionierung
# Version: 3.0.0

metadata:
  version: "3.3.0"
  description: "OMF Shopfloor 4x3 Grid Layout mit Modul-Positionen"
  last_updated: "2025-09-09"
  author: "OMF Development Team"
  grid_size: "4x3"
  total_positions: 12

# Grid-Definition
grid:
  rows: 3
  columns: 4
  cell_size: "100x100"  # cm
  total_cells: 12

# Modul-Positionen (basierend auf ASCII-Dokumentation)
positions:
  # Zeile 0 (oben)
  - position: [0, 0]
    type: "EMPTY"
    id: "EMPTY_0_0"
    name: "Leer"
    description: "Freie Position"
    enabled: false
    
  - position: [0, 1]
    type: "MODULE"
    id: "MILL"
    name: "MILL"
    name_lang_en: "Mill"
    name_lang_de: "Fräse"
    module_serial: "SVR3QA2098"
    description: "Fräsmodul für Werkstück-Bearbeitung"
    commands: ["PICK", "MILL", "DROP"]
    enabled: true
    
  - position: [0, 2]
    type: "MODULE"
    id: "AIQS"
    name: "AIQS"
    name_lang_en: "AI Quality Station"
    name_lang_de: "KI-Qualitätssicherung"
    module_serial: "SVR4H76530"
    description: "KI-gestützte Qualitätsprüfung"
    commands: ["PICK", "CHECK_QUALITY", "DROP"]
    enabled: true
    
  - position: [0, 3]
    type: "EMPTY"
    id: "EMPTY_0_3"
    name: "Leer"
    description: "Freie Position"
    enabled: false

  # Zeile 1 (mitte)
  - position: [1, 0]
    type: "MODULE"
    id: "HBW"
    name: "HBW"
    name_lang_en: "High Bay Warehouse"
    name_lang_de: "Hochregallager"
    module_serial: "SVR3QA0022"
    description: "Hochregallager für Werkstück-Lagerung"
    commands: ["PICK", "DROP", "STORE"]
    enabled: true
    
  - position: [1, 1]
    type: "INTERSECTION"
    id: "Intersection1"
    name: "I1"
    name_lang_en: "Intersection 1"
    name_lang_de: "Kreuzung 1"
    description: "Kreuzungspunkt HBW ↔ MILL"
    connected_modules: ["HBW", "MILL"]
    mqtt_id: "1"  # Für MQTT-Messages
    enabled: true
    
  - position: [1, 2]
    type: "INTERSECTION"
    id: "Intersection2"
    name: "I2"
    name_lang_en: "Intersection 2"
    name_lang_de: "Kreuzung 2"
    description: "Kreuzungspunkt MILL ↔ AIQS ↔ DPS"
    connected_modules: ["MILL", "AIQS", "DPS"]
    mqtt_id: "2"  # Für MQTT-Messages
    enabled: true
    
  - position: [1, 3]
    type: "MODULE"
    id: "DPS"
    name: "DPS"
    name_lang_en: "Drill Processing Station"
    name_lang_de: "Bohr-Verarbeitungsstation"
    module_serial: "SVR4H73275"
    description: "Bohr-Verarbeitungsstation"
    commands: ["PICK", "DRILL", "DROP"]
    enabled: true

  # Zeile 2 (unten)
  - position: [2, 0]
    type: "MODULE"
    id: "DRILL"
    name: "DRILL"
    name_lang_en: "Drill"
    name_lang_de: "Bohrer"
    module_serial: "SVR4H76449"
    description: "Bohrmodul für Werkstück-Bearbeitung"
    commands: ["PICK", "DRILL", "DROP"]
    enabled: true
    
  - position: [2, 1]
    type: "INTERSECTION"
    id: "Intersection3"
    name: "I3"
    name_lang_en: "Intersection 3"
    name_lang_de: "Kreuzung 3"
    description: "Kreuzungspunkt DRILL ↔ HBW"
    connected_modules: ["DRILL", "HBW"]
    mqtt_id: "3"  # Für MQTT-Messages
    enabled: true
    
  - position: [2, 2]
    type: "INTERSECTION"
    id: "Intersection4"
    name: "I4"
    name_lang_en: "Intersection 4"
    name_lang_de: "Kreuzung 4"
    description: "Kreuzungspunkt DRILL ↔ CHRG ↔ DPS"
    connected_modules: ["DRILL", "CHRG0", "DPS"]
    mqtt_id: "4"  # Für MQTT-Messages
    enabled: true
    
  - position: [2, 3]
    type: "MODULE"
    id: "CHRG0"
    name: "CHRG"
    name_lang_en: "Charging Station"
    name_lang_de: "Ladestation"
    module_serial: "5iO4"  # FTS Serial
    description: "FTS-Ladestation"
    commands: ["DOCK", "UNDOCK", "CHARGE"]
    enabled: true
    icon: "🔌"

# Shopfloor-Metadaten
shopfloor_metadata:
  total_modules: 6
  total_intersections: 4
  total_empty_positions: 2
  fts_start_position: "CHRG0"
  storage_position: "HBW"
  output_position: "DPS"
  processing_modules: ["DRILL", "MILL", "AIQS"]
  transport_modules: ["FTS"]
