# OMF Topic Configuration
# Zentrale Konfigurationsdatei für MQTT-Topics
# Version: 3.0.0

metadata:
  version: "3.0.0"
  description: "OMF MQTT Topic-Konfiguration für ORBIS Modellfabrik"
  last_updated: "2025-08-29"
  author: "OMF Development Team"

# Topic-Kategorien mit Beschreibungen
categories:
  CCU:
    description: "Zentrale Steuerungseinheit (Central Control Unit) - Koordiniert alle Module und Workflows"
    icon: "🏭"
    
  TXT:
    description: "TXT 4.0 Controller - Fischertechnik Controller für Sensorik und Aktorik"
    icon: "🎛️"
    
  MODULE:
    description: "APS-Module - Einzelne Produktionsmodule (MILL, DRILL, AIQS, DPS, HBW, FTS)"
    icon: "⚙️"
    
  Node-RED:
    description: "Node-RED Gateway - Übersetzt zwischen OPC-UA und MQTT Protokollen"
    icon: "🔄"

# Topic-Konfigurationen
topics:
  # CCU Topics (mit Sub-Kategorien)
  "ccu/state":
    category: "CCU"
    sub_category: "State"
    friendly_name: "CCU : state"
    description: "Zentraler System-Status"
    template: "ccu/state/status"
    template_direction: "inbound"
    
  "ccu/state/flow":
    category: "CCU"
    sub_category: "State"
    friendly_name: "CCU : state : flow"
    description: "Workflow-Status der CCU"
    template: "ccu/state/status"
    template_direction: "inbound"
    
  "ccu/state/status":
    category: "CCU"
    sub_category: "State"
    friendly_name: "CCU : state : status"
    description: "Detaillierter CCU-Status"
    template: "ccu/state/status"
    template_direction: "inbound"
    
  "ccu/state/error":
    category: "CCU"
    sub_category: "State"
    friendly_name: "CCU : state : error"
    description: "CCU-Fehlermeldungen"
    template: "ccu/state/status"
    template_direction: "inbound"
    
  "ccu/control":
    category: "CCU"
    sub_category: "Control"
    friendly_name: "CCU : control"
    description: "CCU-Steuerungsbefehle"
    template: "ccu/control"
    template_direction: "outbound"
    
  "ccu/control/command":
    category: "CCU"
    sub_category: "Control"
    friendly_name: "CCU : control : command"
    description: "Direkte CCU-Befehle"
    template: "ccu/control"
    template_direction: "outbound"
    
  "ccu/control/order":
    category: "CCU"
    sub_category: "Control"
    friendly_name: "CCU : control : order"
    description: "CCU-Auftragssteuerung"
    template: "ccu/control"
    template_direction: "outbound"
    
  "ccu/set/reset":
    category: "CCU"
    sub_category: "Control"
    friendly_name: "CCU : set : reset"
    description: "CCU-Factory-Reset-Befehl"
    template: "ccu/control"
    template_direction: "outbound"
    
  "ccu/status":
    category: "CCU"
    sub_category: "Status"
    friendly_name: "CCU : status"
    description: "Allgemeiner CCU-Status"
    template: "ccu/state/status"
    template_direction: "inbound"
    
  "ccu/status/connection":
    category: "CCU"
    sub_category: "Status"
    friendly_name: "CCU : status : connection"
    description: "CCU-Verbindungsstatus"
    template: "ccu/state/status"
    template_direction: "inbound"
    
  "ccu/status/health":
    category: "CCU"
    sub_category: "Status"
    friendly_name: "CCU : status : health"
    description: "CCU-Gesundheitsstatus"
    template: "ccu/state/status"
    template_direction: "inbound"

  # TXT Controller Topics (mit Sub-Kategorien)
  "/j1/txt/1/f/i/stock":
    category: "TXT"
    sub_category: "Function Input"
    friendly_name: "TXT : f : i : stock"
    description: "TXT Input - Werkstück-Lagerbestand"
    template: "txt/stock_input"
    template_direction: "inbound"
    
  "/j1/txt/1/f/o/order":
    category: "TXT"
    sub_category: "Function Output"
    friendly_name: "TXT : f : o : order"
    description: "TXT Output - Bestellungen"
    
  "/j1/txt/1/f/i/order":
    category: "TXT"
    sub_category: "Function Input"
    friendly_name: "TXT : f : i : order"
    description: "TXT Input - Bestellungen"
    template: "txt/order_input"
    template_direction: "inbound"
    
  "/j1/txt/1/f/o/stock":
    category: "TXT"
    sub_category: "Function Output"
    friendly_name: "TXT : f : o : stock"
    description: "TXT Output - Werkstück-Lagerbestand"
    
  "/j1/txt/1/f/i/status":
    category: "TXT"
    sub_category: "Function Input"
    friendly_name: "TXT : f : i : status"
    description: "TXT Input - Status"
    
  "/j1/txt/1/f/o/status":
    category: "TXT"
    sub_category: "Function Output"
    friendly_name: "TXT : f : o : status"
    description: "TXT Output - Status"
    
  "/j1/txt/1/f/i/error":
    category: "TXT"
    sub_category: "Function Input"
    friendly_name: "TXT : f : i : error"
    description: "TXT Input - Fehlermeldungen"
    
  "/j1/txt/1/f/o/error":
    category: "TXT"
    sub_category: "Function Output"
    friendly_name: "TXT : f : o : error"
    description: "TXT Output - Fehlermeldungen"
    
  "/j1/txt/1/f/i/config/hbw":
    category: "TXT"
    sub_category: "Function Input"
    friendly_name: "TXT : f : i : config : hbw"
    description: "TXT Input - HBW-Konfiguration"
    
  "/j1/txt/1/c/bme680":
    category: "TXT"
    sub_category: "Control"
    friendly_name: "TXT : c : bme680"
    description: "TXT Control - BME680 Sensor"
    template: "txt/sensor_control"
    template_direction: "outbound"
    
  "/j1/txt/1/c/cam":
    category: "TXT"
    sub_category: "Control"
    friendly_name: "TXT : c : cam"
    description: "TXT Control - Kamera"
    template: "txt/sensor_control"
    template_direction: "outbound"
    
  "/j1/txt/1/c/ldr":
    category: "TXT"
    sub_category: "Control"
    friendly_name: "TXT : c : ldr"
    description: "TXT Control - LDR Sensor"
    template: "txt/sensor_control"
    template_direction: "outbound"
    
  "/j1/txt/1/i/bme680":
    category: "TXT"
    sub_category: "Input"
    friendly_name: "TXT : i : bme680"
    description: "TXT Input - BME680 Daten"
    
  "/j1/txt/1/i/broadcast":
    category: "TXT"
    sub_category: "Input"
    friendly_name: "TXT : i : broadcast"
    description: "TXT Input - Broadcast-Nachrichten"
    
  "/j1/txt/1/i/cam":
    category: "TXT"
    sub_category: "Input"
    friendly_name: "TXT : i : cam"
    description: "TXT Input - Kamera-Daten"
    
  "/j1/txt/1/i/ldr":
    category: "TXT"
    sub_category: "Input"
    friendly_name: "TXT : i : ldr"
    description: "TXT Input - LDR-Daten"
    
  "/j1/txt/1/o/broadcast":
    category: "TXT"
    sub_category: "Output"
    friendly_name: "TXT : o : broadcast"
    description: "TXT Output - Broadcast-Nachrichten"

  # Module Topics - MILL
  "module/v1/ff/SVR3QA2098/connection":
    category: "MODULE"
    sub_category: "Connection"
    module: "MILL"
    friendly_name: "MILL : connection"
    description: "MILL-Verbindungsstatus"
    template: "module/connection"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR3QA2098/state":
    category: "MODULE"
    sub_category: "State"
    module: "MILL"
    friendly_name: "MILL : state"
    description: "MILL-Modul-Status"
    template: "module/state"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR3QA2098/order":
    category: "MODULE"
    sub_category: "Order"
    module: "MILL"
    friendly_name: "MILL : order"
    description: "MILL-Befehle/Aufträge"
    template: "module/order"
    template_direction: "outbound"
    
  "module/v1/ff/SVR3QA2098/factsheet":
    category: "MODULE"
    sub_category: "Factsheet"
    module: "MILL"
    friendly_name: "MILL : factsheet"
    description: "MILL-Konfigurationsdaten"
    template: "module/factsheet"
    template_direction: "inbound"

  # Module Topics - DRILL
  "module/v1/ff/SVR4H76449/connection":
    category: "MODULE"
    sub_category: "Connection"
    module: "DRILL"
    friendly_name: "DRILL : connection"
    description: "DRILL-Verbindungsstatus"
    template: "module/connection"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR4H76449/state":
    category: "MODULE"
    sub_category: "State"
    module: "DRILL"
    friendly_name: "DRILL : state"
    description: "DRILL-Modul-Status"
    template: "module/state"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR4H76449/order":
    category: "MODULE"
    sub_category: "Order"
    module: "DRILL"
    friendly_name: "DRILL : order"
    description: "DRILL-Befehle/Aufträge"
    template: "module/order"
    template_direction: "outbound"
    
  "module/v1/ff/SVR4H76449/factsheet":
    category: "MODULE"
    sub_category: "Factsheet"
    module: "DRILL"
    friendly_name: "DRILL : factsheet"
    description: "DRILL-Konfigurationsdaten"
    template: "module/factsheet"
    template_direction: "inbound"

  # Module Topics - AIQS
  "module/v1/ff/SVR4H76530/connection":
    category: "MODULE"
    sub_category: "Connection"
    module: "AIQS"
    friendly_name: "AIQS : connection"
    description: "AIQS-Verbindungsstatus"
    template: "module/connection"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR4H76530/state":
    category: "MODULE"
    sub_category: "State"
    module: "AIQS"
    friendly_name: "AIQS : state"
    description: "AIQS-Modul-Status"
    template: "module/state"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR4H76530/order":
    category: "MODULE"
    sub_category: "Order"
    module: "AIQS"
    friendly_name: "AIQS : order"
    description: "AIQS-Befehle/Aufträge"
    template: "module/order"
    template_direction: "outbound"
    
  "module/v1/ff/SVR4H76530/factsheet":
    category: "MODULE"
    sub_category: "Factsheet"
    module: "AIQS"
    friendly_name: "AIQS : factsheet"
    description: "AIQS-Konfigurationsdaten"
    template: "module/factsheet"
    template_direction: "inbound"

  # Module Topics - DPS
  "module/v1/ff/SVR4H73275/connection":
    category: "MODULE"
    sub_category: "Connection"
    module: "DPS"
    friendly_name: "DPS : connection"
    description: "DPS-Verbindungsstatus"
    template: "module/connection"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR4H73275/state":
    category: "MODULE"
    sub_category: "State"
    module: "DPS"
    friendly_name: "DPS : state"
    description: "DPS-Modul-Status"
    template: "module/state"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR4H73275/order":
    category: "MODULE"
    sub_category: "Order"
    module: "DPS"
    friendly_name: "DPS : order"
    description: "DPS-Befehle/Aufträge"
    template: "module/order"
    template_direction: "outbound"
    
  "module/v1/ff/SVR4H73275/factsheet":
    category: "MODULE"
    sub_category: "Factsheet"
    module: "DPS"
    friendly_name: "DPS : factsheet"
    description: "DPS-Konfigurationsdaten"
    template: "module/factsheet"
    template_direction: "inbound"

  # Module Topics - HBW
  "module/v1/ff/SVR3QA0022/connection":
    category: "MODULE"
    sub_category: "Connection"
    module: "HBW"
    friendly_name: "HBW : connection"
    description: "HBW-Verbindungsstatus"
    template: "module/connection"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR3QA0022/state":
    category: "MODULE"
    sub_category: "State"
    module: "HBW"
    friendly_name: "HBW : state"
    description: "HBW-Modul-Status"
    template: "module/state"
    template_direction: "bidirectional"
    
  "module/v1/ff/SVR3QA0022/order":
    category: "MODULE"
    sub_category: "Order"
    module: "HBW"
    friendly_name: "HBW : order"
    description: "HBW-Befehle/Aufträge"
    template: "module/order"
    template_direction: "outbound"
    
  "module/v1/ff/SVR3QA0022/factsheet":
    category: "MODULE"
    sub_category: "Factsheet"
    module: "HBW"
    friendly_name: "HBW : factsheet"
    description: "HBW-Konfigurationsdaten"
    template: "module/factsheet"
    template_direction: "inbound"

  # Node-RED Topics (mit Sub-Kategorien wie Module)
  "module/v1/ff/NodeRed/SVR4H76530/connection":
    category: "Node-RED"
    sub_category: "Connection"
    module: "AIQS"
    friendly_name: "NodeRed → AIQS : connection"
    description: "Node-RED Gateway - AIQS-Verbindung"
    template: "connection"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H76530/state":
    category: "Node-RED"
    sub_category: "State"
    module: "AIQS"
    friendly_name: "NodeRed → AIQS : state"
    description: "Node-RED Gateway - AIQS-Status"
    template: "state"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H76530/factsheet":
    category: "Node-RED"
    sub_category: "Factsheet"
    module: "AIQS"
    friendly_name: "NodeRed → AIQS : factsheet"
    description: "Node-RED Gateway - AIQS-Konfiguration"
    template: "factsheet"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H73275/connection":
    category: "Node-RED"
    sub_category: "Connection"
    module: "DPS"
    friendly_name: "NodeRed → DPS : connection"
    description: "Node-RED Gateway - DPS-Verbindung"
    template: "connection"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H73275/state":
    category: "Node-RED"
    sub_category: "State"
    module: "DPS"
    friendly_name: "NodeRed → DPS : state"
    description: "Node-RED Gateway - DPS-Status"
    template: "state"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H73275/factsheet":
    category: "Node-RED"
    sub_category: "Factsheet"
    module: "DPS"
    friendly_name: "NodeRed → DPS : factsheet"
    description: "Node-RED Gateway - DPS-Konfiguration"
    template: "factsheet"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H76449/connection":
    category: "Node-RED"
    sub_category: "Connection"
    module: "DRILL"
    friendly_name: "NodeRed → DRILL : connection"
    description: "Node-RED Gateway - DRILL-Verbindung"
    template: "connection"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H76449/state":
    category: "Node-RED"
    sub_category: "State"
    module: "DRILL"
    friendly_name: "NodeRed → DRILL : state"
    description: "Node-RED Gateway - DRILL-Status"
    template: "state"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR4H76449/factsheet":
    category: "Node-RED"
    sub_category: "Factsheet"
    module: "DRILL"
    friendly_name: "NodeRed → DRILL : factsheet"
    description: "Node-RED Gateway - DRILL-Konfiguration"
    template: "factsheet"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR3QA2098/connection":
    category: "Node-RED"
    sub_category: "Connection"
    module: "MILL"
    friendly_name: "NodeRed → MILL : connection"
    description: "Node-RED Gateway - MILL-Verbindung"
    template: "connection"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR3QA2098/state":
    category: "Node-RED"
    sub_category: "State"
    module: "MILL"
    friendly_name: "NodeRed → MILL : state"
    description: "Node-RED Gateway - MILL-Status"
    template: "state"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR3QA2098/factsheet":
    category: "Node-RED"
    sub_category: "Factsheet"
    module: "MILL"
    friendly_name: "NodeRed → MILL : factsheet"
    description: "Node-RED Gateway - MILL-Konfiguration"
    template: "factsheet"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR3QA0022/connection":
    category: "Node-RED"
    sub_category: "Connection"
    module: "HBW"
    friendly_name: "NodeRed → HBW : connection"
    description: "Node-RED Gateway - HBW-Verbindung"
    template: "connection"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR3QA0022/state":
    category: "Node-RED"
    sub_category: "State"
    module: "HBW"
    friendly_name: "NodeRed → HBW : state"
    description: "Node-RED Gateway - HBW-Status"
    template: "state"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/SVR3QA0022/factsheet":
    category: "Node-RED"
    sub_category: "Factsheet"
    module: "HBW"
    friendly_name: "NodeRed → HBW : factsheet"
    description: "Node-RED Gateway - HBW-Konfiguration"
    template: "factsheet"
    template_direction: "inbound"
    
  "module/v1/ff/NodeRed/status":
    category: "Node-RED"
    sub_category: "Status"
    friendly_name: "NodeRed : status"
    description: "Node-RED Gateway-Status"
    template: "status"
    template_direction: "inbound"

  # FTS Topics (behandelt wie Modul)
  "fts/v1/ff/5iO4/connection":
    category: "MODULE"
    sub_category: "Connection"
    module: "FTS"
    friendly_name: "FTS : connection"
    description: "FTS-Verbindungsstatus"
    
  "fts/v1/ff/5iO4/state":
    category: "MODULE"
    sub_category: "State"
    module: "FTS"
    friendly_name: "FTS : state"
    description: "FTS-System-Status"
    
  "fts/v1/ff/5iO4/order":
    category: "MODULE"
    sub_category: "Order"
    module: "FTS"
    friendly_name: "FTS : order"
    description: "FTS-Navigationsbefehle"
    
  "fts/v1/ff/5iO4/factsheet":
    category: "MODULE"
    sub_category: "Factsheet"
    module: "FTS"
    friendly_name: "FTS : factsheet"
    description: "FTS-Konfigurationsdaten"

# Sub-Kategorien für Module
module_sub_categories:
  Connection:
    description: "Verbindungsstatus zwischen Modul und CCU"
    icon: "🔗"
    
  State:
    description: "Aktueller Modul-Status und Betriebszustand"
    icon: "📊"
    
  Order:
    description: "Befehle und Aufträge an das Modul"
    icon: "📋"
    
  Factsheet:
    description: "Modul-Konfiguration und Metadaten"
    icon: "📄"

# Template-Integration
template_placeholders:
  module_id: "<moduleId>"
  module_name: "<moduleName>"
  category: "<category>"
  sub_category: "<subCategory>"

# MQTT-Topic-Pfade für Topic-Erkennung
topic_patterns:
  - ["category"]
  - ["module"]
  - ["sub_category"]
