metadata:
  category: MODULE
  description: Module Connection Message Template
  template_type: "message_structure_definition"
  last_updated: "2025-08-29"
  version: 3.0.0

# TEMPLATE: Message-Struktur-Definition
template:
  name: "module/connection"
  description: "Module Connection Status - Message Structure Definition"
  semantic_purpose: "Verbindungsstatus eines Moduls überwachen"
  
  # SYNTAX: Struktur der Nachricht
  structure:
    required_fields:
      - module_id
      - connected
      - timestamp
    optional_fields:
      - ip
      - serialNumber
      - version
      - manufacturer
    
    field_definitions:
      module_id:
        type: "string"
        pattern: "enum"
        description: "Serial Number des Moduls"
        validation: "must be valid module serial number"
        
      connected:
        type: "boolean"
        description: "Verbindungsstatus"
        validation: "must be true or false"
        
      ip:
        type: "string"
        pattern: "ipv4"
        description: "IP-Adresse des Moduls"
        validation: "must be valid IPv4 address"
        
      serialNumber:
        type: "string"
        pattern: "enum"
        description: "Serial Number (redundant zu module_id)"
        validation: "must match module_id"
        
      version:
        type: "string"
        pattern: "semver"
        description: "Modul-Version"
        validation: "must be valid semantic version"
        
      manufacturer:
        type: "string"
        pattern: "enum"
        description: "Hersteller"
        validation: "must be 'Fischertechnik'"
        
      timestamp:
        type: "string"
        pattern: "iso8601"
        description: "Zeitstempel"
        validation: "must be ISO 8601 format"
  
  # SEMANTICS: Validierungsregeln
  validation_rules:
    - "timestamp muss ISO 8601 Format haben"
    - "connected muss boolean sein"
    - "module_id muss gültige Serial Number sein"
    - "ip muss gültige IP-Adresse sein"
    - "version muss gültige Versionsnummer sein"
    - "serialNumber muss mit module_id übereinstimmen"
    - "manufacturer muss 'Fischertechnik' sein"
  
  # VARIABLE FIELDS: Enum-Werte für Generierung
  variable_fields:
    module_id:
      type: "enum"
      values: ["SVR3QA0022", "SVR4H76449", "SVR3QA2098", "SVR4H76530", "SVR4H73275", "CHRG0"]
      description: "Serial Number des Moduls"
      
    ip:
      type: "enum"
      values: ["192.168.0.40", "192.168.0.41", "192.168.0.42", "192.168.0.43", "192.168.0.44", "192.168.0.45", "192.168.0.50", "192.168.0.51", "192.168.0.52", "192.168.0.53", "192.168.0.54", "192.168.0.55", "192.168.0.65", "192.168.0.70", "192.168.0.71", "192.168.0.72", "192.168.0.73", "192.168.0.74", "192.168.0.75", "192.168.0.80", "192.168.0.81", "192.168.0.82", "192.168.0.83", "192.168.0.90"]
      description: "IP-Adresse des Moduls"
      
    version:
      type: "enum"
      values: ["1.3.0", "1.0.0"]
      description: "Version des Moduls"
      
    manufacturer:
      type: "enum"
      values: ["Fischertechnik"]
      description: "Hersteller"
  
  # MQTT INTEGRATION
  mqtt:
    topic_pattern: "module/v1/ff/{module_id}/connection"
    direction: "bidirectional"
    qos: 1
    retain: false
    
  # USAGE EXAMPLES (mehrere Beispiele für besseres Verständnis)
  usage_examples:
    - description: "Modul verbunden (HBW)"
      topic: "module/v1/ff/SVR3QA0022/connection"
      payload:
        module_id: "SVR3QA0022"
        connected: true
        ip: "192.168.0.80"
        serialNumber: "SVR3QA0022"
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:00:00Z"
        
    - description: "Modul verbunden (MILL)"
      topic: "module/v1/ff/SVR3QA2098/connection"
      payload:
        module_id: "SVR3QA2098"
        connected: true
        ip: "192.168.0.40"
        serialNumber: "SVR3QA2098"
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:05:00Z"
        
    - description: "Modul getrennt (DRILL)"
      topic: "module/v1/ff/SVR4H76449/connection"
      payload:
        module_id: "SVR4H76449"
        connected: false
        ip: "192.168.0.50"
        serialNumber: "SVR4H76449"
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:10:00Z"
        
    - description: "Modul verbunden (AIQS)"
      topic: "module/v1/ff/SVR4H76530/connection"
      payload:
        module_id: "SVR4H76530"
        connected: true
        ip: "192.168.0.70"
        serialNumber: "SVR4H76530"
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:15:00Z"
