metadata:
  category: MODULE
  description: HBW Inventory State Templates - Spezifisch für Lagerbestand-Management
  icon: 📦
  last_updated: '2025-01-04'
  sub_category: State
  version: 3.0.0
  purpose: "Template für HBW-Lagerbestand-Updates mit zeitlichen Abhängigkeiten"

templates:
  # HBW Lagerbestand State - Vereinfacht für Dashboard-Integration
  "module/v1/ff/SVR3QA0022/state":
    category: MODULE
    description: "HBW Lagerbestand Status - Aktuelle Belegung aller 9 Positionen (A1-C3)"
    module: "SVR3QA0022"
    sub_category: "State"
    template_structure:
      loads: "Array von Werkstück-Objekten"
      timestamp: "ISO 8601 Format oder Unix timestamp"
      metadata:
        opcuaState: "connected|disconnected"
        updateType: "initial|delta|full"
      serialNumber: "SVR3QA0022"
    
    # Vereinfachte Beispiele für Dashboard-Integration
    examples:
      # Initial State - Vollständiger Lagerbestand
      - description: "Erste Nachricht mit vollständigem Lagerbestand"
        payload: |
          {
            "loads": [
              {"loadType": "RED", "loadPosition": "A1", "loadId": "red_001"},
              {"loadType": "BLUE", "loadPosition": "A2", "loadId": "blue_001"},
              {"loadType": "WHITE", "loadPosition": "A3", "loadId": "white_001"},
              {"loadType": "RED", "loadPosition": "B1", "loadId": "red_002"},
              {"loadType": "BLUE", "loadPosition": "B2", "loadId": "blue_002"},
              {"loadType": "WHITE", "loadPosition": "B3", "loadId": "white_002"},
              {"loadType": "RED", "loadPosition": "C1", "loadId": "red_003"},
              {"loadType": "BLUE", "loadPosition": "C2", "loadId": "blue_003"},
              {"loadType": "WHITE", "loadPosition": "C3", "loadId": "white_003"}
            ],
            "timestamp": "2025-01-04T10:30:00Z",
            "metadata": {
              "opcuaState": "connected",
              "updateType": "initial"
            },
            "serialNumber": "SVR3QA0022"
          }
      
      # Delta Update - Nur geänderte Positionen
      - description: "Folge-Nachrichten mit Änderungen"
        payload: |
          {
            "loads": [
              {"loadType": "RED", "loadPosition": "A1", "loadId": "red_001"},
              {"loadType": "BLUE", "loadPosition": "A2", "loadId": "blue_001"}
            ],
            "timestamp": "2025-01-04T10:31:00Z",
            "metadata": {
              "opcuaState": "connected",
              "updateType": "delta"
            },
            "serialNumber": "SVR3QA0022"
          }
      
      # Empty Warehouse - Leeres Lager
      - description: "Leeres Lager nach Reset"
        payload: |
          {
            "loads": [],
            "timestamp": "2025-01-04T10:32:00Z",
            "metadata": {
              "opcuaState": "connected",
              "updateType": "full"
            },
            "serialNumber": "SVR3QA0022"
          }
      
      # Partial Update - Einzelne Position geändert
      - description: "Einzelne Position wurde geändert"
        payload: |
          {
            "loads": [
              {"loadType": "WHITE", "loadPosition": "B2", "loadId": "white_004"}
            ],
            "timestamp": "2025-01-04T10:33:00Z",
            "metadata": {
              "opcuaState": "connected",
              "updateType": "delta"
            },
            "serialNumber": "SVR3QA0022"
          }
      
      # Unix Timestamp Format (wie in Session-Daten)
      - description: "Unix Timestamp Format aus Session-Daten"
        payload: |
          {
            "loads": [
              {"loadType": "RED", "loadPosition": "A1", "loadId": "red_001"},
              {"loadType": "BLUE", "loadPosition": "A2", "loadId": "blue_001"},
              {"loadType": "WHITE", "loadPosition": "A3", "loadId": "white_001"}
            ],
            "timestamp": 1756980963.7231271,
            "metadata": {
              "opcuaState": "connected",
              "updateType": "initial"
            },
            "serialNumber": "SVR3QA0022"
          }
    
    # Validierungsregeln für Dashboard-Integration
    validation_rules:
      - "serialNumber muss 'SVR3QA0022' sein"
      - "timestamp muss ISO 8601 Format oder Unix timestamp sein"
      - "loads muss Array von Objekten sein"
      - "loadType muss in ['RED', 'BLUE', 'WHITE', ''] sein"
      - "loadPosition muss in ['A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'C1', 'C2', 'C3'] sein"
      - "loadId muss String sein (kann leer sein für leere Positionen)"
      - "metadata.opcuaState muss in ['connected', 'disconnected'] sein"
      - "metadata.updateType muss in ['initial', 'delta', 'full'] sein"
    
    # Zeitliche Abhängigkeiten
    temporal_dependencies:
      first_message:
        description: "Vollständiger Lagerbestand als Basis-Zustand"
        characteristics:
          - "Enthält alle belegten Positionen"
          - "updateType: 'initial'"
          - "Timestamp: Erste Nachricht der Session"
      
      subsequent_messages:
        description: "Nur geänderte Positionen (Delta-Updates)"
        characteristics:
          - "Enthält nur geänderte Positionen"
          - "updateType: 'delta'"
          - "Timestamp: Zeitpunkt der Änderung"
      
      full_update:
        description: "Vollständige Aktualisierung (z.B. nach Reset)"
        characteristics:
          - "Enthält kompletten aktuellen Zustand"
          - "updateType: 'full'"
          - "Timestamp: Zeitpunkt der Vollaktualisierung"
    
    # Dashboard-Integration Hinweise
    dashboard_integration:
      inventory_display:
        description: "Für 3x3 Grid-Darstellung (A1-C3)"
        usage: "Übersetzung der loads in visuelle Darstellung"
        position_mapping:
          "A1": "Zeile 1, Spalte 1"
          "A2": "Zeile 1, Spalte 2"
          "A3": "Zeile 1, Spalte 3"
          "B1": "Zeile 2, Spalte 1"
          "B2": "Zeile 2, Spalte 2"
          "B3": "Zeile 2, Spalte 3"
          "C1": "Zeile 3, Spalte 1"
          "C2": "Zeile 3, Spalte 2"
          "C3": "Zeile 3, Spalte 3"
      
      update_handling:
        initial_state: "Dashboard initialisiert mit vollständigem Zustand"
        delta_updates: "Dashboard aktualisiert nur geänderte Positionen"
        error_handling: "Bei Fehlern: Vollständige Neuinitialisierung"
      
      performance_optimization:
        description: "Optimierungen für Dashboard-Performance"
        recommendations:
          - "Delta-Updates bevorzugen für bessere Performance"
          - "Caching des letzten vollständigen Zustands"
          - "Debouncing bei häufigen Updates"
          - "Validierung vor Dashboard-Update"

# Zusätzliche Templates für HBW-Order (Bestellungen)
  "module/v1/ff/SVR3QA0022/order":
    category: MODULE
    description: "HBW Bestellungen senden - Werkstück-Einlagerung oder -Auslagerung"
    module: "SVR3QA0022"
    sub_category: "Order"
    template_structure:
      orderType: "STORAGE|RETRIEVAL"
      workpieceType: "RED|BLUE|WHITE"
      quantity: "integer"
      priority: "normal|high|urgent"
      targetPosition: "A1|A2|A3|B1|B2|B3|C1|C2|C3"  # Optional für STORAGE
      orderId: "UUID string"
      timestamp: "ISO 8601 Format"
    
    examples:
      # Storage Order - Werkstück einlagern
      - description: "Werkstück einlagern"
        payload: |
          {
            "orderType": "STORAGE",
            "workpieceType": "RED",
            "quantity": 1,
            "priority": "normal",
            "targetPosition": "A1",
            "orderId": "550e8400-e29b-41d4-a716-446655440000",
            "timestamp": "2025-01-04T10:30:00Z"
          }
      
      # Retrieval Order - Werkstück auslagern
      - description: "Werkstück auslagern"
        payload: |
          {
            "orderType": "RETRIEVAL",
            "workpieceType": "BLUE",
            "quantity": 1,
            "priority": "normal",
            "orderId": "550e8400-e29b-41d4-a716-446655440001",
            "timestamp": "2025-01-04T10:31:00Z"
          }
      
      # Bulk Storage - Mehrere Werkstücke einlagern
      - description: "Mehrere Werkstücke einlagern"
        payload: |
          {
            "orderType": "STORAGE",
            "workpieceType": "WHITE",
            "quantity": 3,
            "priority": "high",
            "targetPositions": ["A1", "A2", "A3"],
            "orderId": "550e8400-e29b-41d4-a716-446655440002",
            "timestamp": "2025-01-04T10:32:00Z"
          }
    
    validation_rules:
      - "orderType muss in ['STORAGE', 'RETRIEVAL'] sein"
      - "workpieceType muss in ['RED', 'BLUE', 'WHITE'] sein"
      - "quantity muss positive Ganzzahl sein"
      - "priority muss in ['normal', 'high', 'urgent'] sein"
      - "targetPosition muss in ['A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'C1', 'C2', 'C3'] sein (für STORAGE)"
      - "orderId muss gültige UUID sein"
      - "timestamp muss ISO 8601 Format sein"
    
    error_handling:
      timeout: "30_seconds"
      retry_attempts: 3
      error_topics: ["module/v1/ff/SVR3QA0022/error"]
      success_confirmation: "module/v1/ff/SVR3QA0022/state"
