features:
  workpiece_management:
    enabled: true
    description: "Werkst체ck-Verwaltung und -Konfiguration"
    
  message_center:
    enabled: true
    description: "Nachrichten-Zentrale f체r interne Kommunikation"
    
  advanced_logging:
    enabled: true
    description: "Erweiterte Logging-Funktionen"
    
  i18n_support:
    enabled: true
    description: "Mehrsprachige Benutzeroberfl채che"
    
  registry_integration:
    enabled: true
    description: "Integration mit Registry-System"
    
  real_time_updates:
    enabled: true
    description: "Echzeit-Updates f체r Logs und Nachrichten"
    
  user_roles:
    enabled: true
    description: "Rollenbasierte Zugriffskontrolle"

experimental:
  auto_configuration:
    enabled: false
    description: "Automatische Konfigurationserkennung"
    
  machine_learning:
    enabled: false
    description: "ML-basierte Optimierungen"