# MQTT Settings Configuration for OMF2
# This file contains technical MQTT broker settings and environment configurations

environments:
  live:
    description: "Live production environment"
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    client_id_prefix: "omf2_live"
    enabled: true
    tls: false
    keepalive: 60
    clean_session: true
    
  replay:
    description: "Replay/simulation environment"
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    client_id_prefix: "omf2_replay"
    enabled: true
    tls: false
    keepalive: 60
    clean_session: true
    
  mock:
    description: "Mock/testing environment"
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    client_id_prefix: "omf2_mock"
    enabled: true
    tls: false
    keepalive: 60
    clean_session: true

# Default environment selection
default_environment: "replay"

# Global MQTT settings
connection_timeout: 60
qos_default: 1
buffer_size: 1000
message_history_size: 10000

# Logging settings for MQTT
logging:
  level: "INFO"
  log_connections: true
  log_messages: false  # Set to true for detailed message logging
  log_subscriptions: true