# User Roles Configuration for OMF2
# Defines user roles and permissions

roles:
  admin:
    name: "Administrator"
    description: "Full system access and administration"
    permissions:
      - "*"  # Wildcard for all permissions
    ui_components:
      - "ccu_dashboard"
      - "message_center"
      - "system_logs"
      - "admin_settings"
      - "steering_factory"
    color: "#FF4B4B"  # Red
    
  supervisor:
    name: "Supervisor"
    description: "Operational oversight and control"
    permissions:
      - "read"
      - "control"
      - "manage_workflows"
      - "view_logs"
    ui_components:
      - "ccu_dashboard"
      - "message_center"
      - "system_logs"
      - "steering_factory"
    color: "#FF8C00"  # Orange
    
  operator:
    name: "Operator"
    description: "System operation and basic control"
    permissions:
      - "read"
      - "control"
      - "operate_systems"
    ui_components:
      - "ccu_dashboard"
      - "message_center"
    color: "#1f77b4"  # Blue
    
  viewer:
    name: "Viewer"
    description: "Read-only access to system information"
    permissions:
      - "read"
    ui_components:
      - "ccu_dashboard"
    color: "#2ca02c"  # Green

# User assignments
users:
  admin:
    role: "admin"
    name: "System Administrator"
    email: "admin@orbis-modellfabrik.de"
    active: true
    created_at: "2024-01-01T00:00:00Z"
    
  operator1:
    role: "operator"
    name: "Operator User"
    email: "operator@orbis-modellfabrik.de"
    active: true
    created_at: "2024-01-01T00:00:00Z"
    
  guest:
    role: "viewer"
    name: "Guest User"
    email: "guest@orbis-modellfabrik.de"
    active: true
    created_at: "2024-01-01T00:00:00Z"

# Default settings
default_role: "viewer"
session_timeout: 3600  # seconds
require_authentication: false  # Set to true to enable authentication