metadata:
  category: MODULE
  description: Generated connection Templates
  generated: true
  icon: 🔗
  last_updated: '2025-08-29'
  source: module_config.yml
  sub_category: Connection
  version: 3.0.0
templates:
  module/v1/ff/CHRG0/connection:
    category: MODULE
    description: Module CHRG0 Connection
    examples:
    - connectionState: ONLINE
      headerId: 26
      ip: 192.168.0.65
      manufacturer: Fischertechnik
      serialNumber: CHRG0
      timestamp: '2025-08-19T09:13:34.483Z'
      version: 1.3.0
    module: CHRG0
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: <string>
      ip: '[192.168.0.65]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[CHRG0]'
      timestamp: <datetime>
      version: '[1.3.0]'
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - ip muss in [192.168.0.65] sein
    - version muss in [1.3.0] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [CHRG0] sein
    - connectionState muss in [ONLINE] sein
  module/v1/ff/SVR3QA0022/connection:
    category: MODULE
    description: Module SVR3QA0022 Connection
    examples:
    - connectionState: ONLINE
      headerId: 26
      ip: 192.168.0.80
      manufacturer: Fischertechnik
      serialNumber: SVR3QA0022
      timestamp: '2025-08-19T09:13:34.483Z'
      version: 1.3.0
    module: SVR3QA0022
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: <string>
      ip: '[192.168.0.80]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[SVR3QA0022]'
      timestamp: <datetime>
      version: '[1.3.0]'
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - ip muss in [192.168.0.80] sein
    - version muss in [1.3.0] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [SVR3QA0022] sein
    - connectionState muss in [ONLINE] sein
  module/v1/ff/SVR3QA2098/connection:
    category: MODULE
    description: Module SVR3QA2098 Connection
    examples:
    - connectionState: ONLINE
      headerId: 26
      ip: 192.168.0.40
      manufacturer: Fischertechnik
      serialNumber: SVR3QA2098
      timestamp: '2025-08-19T09:13:34.483Z'
      version: 1.3.0
    module: SVR3QA2098
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: <string>
      ip: '[192.168.0.40]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[SVR3QA2098]'
      timestamp: <datetime>
      version: '[1.3.0]'
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - ip muss in [192.168.0.40] sein
    - version muss in [1.3.0] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [SVR3QA2098] sein
    - connectionState muss in [ONLINE] sein
  module/v1/ff/SVR4H73275/connection:
    category: MODULE
    description: Module SVR4H73275 Connection
    examples:
    - connectionState: ONLINE
      headerId: 26
      ip: 192.168.0.90
      manufacturer: Fischertechnik
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:13:34.483Z'
      version: 1.3.0
    module: SVR4H73275
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: <string>
      ip: '[192.168.0.90]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[SVR4H73275]'
      timestamp: <datetime>
      version: '[1.3.0]'
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - ip muss in [192.168.0.90] sein
    - version muss in [1.3.0] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [SVR4H73275] sein
    - connectionState muss in [ONLINE] sein
  module/v1/ff/SVR4H76449/connection:
    category: MODULE
    description: Module SVR4H76449 Connection
    examples:
    - connectionState: ONLINE
      headerId: 26
      ip: 192.168.0.50
      manufacturer: Fischertechnik
      serialNumber: SVR4H76449
      timestamp: '2025-08-19T09:13:34.483Z'
      version: 1.3.0
    module: SVR4H76449
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: <string>
      ip: '[192.168.0.50]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[SVR4H76449]'
      timestamp: <datetime>
      version: '[1.3.0]'
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - ip muss in [192.168.0.50] sein
    - version muss in [1.3.0] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [SVR4H76449] sein
    - connectionState muss in [ONLINE] sein
  module/v1/ff/SVR4H76530/connection:
    category: MODULE
    description: Module SVR4H76530 Connection
    examples:
    - connectionState: ONLINE
      headerId: 26
      ip: 192.168.0.70
      manufacturer: Fischertechnik
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:13:34.483Z'
      version: 1.3.0
    module: SVR4H76530
    sub_category: Connection
    template_structure:
      connectionState: '[ONLINE]'
      headerId: <string>
      ip: '[192.168.0.70]'
      manufacturer: '[Fischertechnik]'
      serialNumber: '[SVR4H76530]'
      timestamp: <datetime>
      version: '[1.3.0]'
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - ip muss in [192.168.0.70] sein
    - version muss in [1.3.0] sein
    - manufacturer muss in [Fischertechnik] sein
    - serialNumber muss in [SVR4H76530] sein
    - connectionState muss in [ONLINE] sein
