metadata:
  category: MODULE
  description: Module Factsheet Message Template
  template_type: "message_structure_definition"
  last_updated: "2025-08-29"
  version: 3.0.0

# TEMPLATE: Message-Struktur-Definition
template:
  name: "module/factsheet"
  description: "Module Factsheet - Message Structure Definition"
  semantic_purpose: "Modul-Konfigurationsdaten abrufen"
  
  # SYNTAX: Struktur der Nachricht
  structure:
    required_fields:
      - module_id
      - name
      - type
      - sub_type
      - description
      - enabled
      - timestamp
    optional_fields:
      - ip_addresses
      - commands
      - version
      - manufacturer
    
    field_definitions:
      module_id:
        type: "string"
        pattern: "enum"
        description: "Serial Number des Moduls"
        validation: "must be valid module serial number"
        
      name:
        type: "string"
        pattern: "enum"
        description: "Name des Moduls"
        validation: "must be valid module name"
        
      type:
        type: "string"
        pattern: "enum"
        description: "Typ des Moduls"
        validation: "must be valid module type"
        
      sub_type:
        type: "string"
        pattern: "enum"
        description: "Sub-Typ des Moduls"
        validation: "must be valid module sub-type"
        
      description:
        type: "string"
        description: "Beschreibung des Moduls"
        validation: "must be non-empty string"
        
      ip_addresses:
        type: "array"
        description: "IP-Adressen des Moduls"
        validation: "array of valid IPv4 addresses"
        
      commands:
        type: "array"
        description: "Verfügbare Commands"
        validation: "array of valid commands"
        
      enabled:
        type: "boolean"
        description: "Modul aktiviert"
        validation: "must be true or false"
        
      version:
        type: "string"
        pattern: "semver"
        description: "Modul-Version"
        validation: "must be valid semantic version"
        
      manufacturer:
        type: "string"
        pattern: "enum"
        description: "Hersteller"
        validation: "must be 'Fischertechnik'"
        
      timestamp:
        type: "string"
        pattern: "iso8601"
        description: "Zeitstempel"
        validation: "must be ISO 8601 format"
  
  # SEMANTICS: Validierungsregeln
  validation_rules:
    - "timestamp muss ISO 8601 Format haben"
    - "module_id muss gültige Serial Number sein"
    - "name muss gültiger Modul-Name sein"
    - "type muss gültiger Modul-Typ sein"
    - "sub_type muss gültiger Sub-Typ sein"
    - "enabled muss boolean sein"
    - "description muss nicht leer sein"
    - "ip_addresses muss Array von gültigen IP-Adressen sein"
    - "commands muss Array von gültigen Commands sein"
    - "manufacturer muss 'Fischertechnik' sein"
  
  # VARIABLE FIELDS: Enum-Werte für Generierung
  variable_fields:
    module_id:
      type: "enum"
      values: ["SVR3QA0022", "SVR4H76449", "SVR3QA2098", "SVR4H76530", "SVR4H73275", "CHRG0"]
      description: "Serial Number des Moduls"
      
    name:
      type: "enum"
      values: ["HBW", "DRILL", "MILL", "AIQS", "DPS", "CHRG"]
      description: "Name des Moduls"
      
    type:
      type: "enum"
      values: ["Storage", "Processing", "Quality-Control", "Input/Output", "Charging"]
      description: "Typ des Moduls"
      
    sub_type:
      type: "enum"
      values: ["HBW", "DRILL", "MILL", "AIQS", "DPS", "CHRG"]
      description: "Sub-Typ des Moduls"
      
    version:
      type: "enum"
      values: ["1.3.0", "1.0.0"]
      description: "Version des Moduls"
      
    manufacturer:
      type: "enum"
      values: ["Fischertechnik"]
      description: "Hersteller"
  
  # MQTT INTEGRATION
  mqtt:
    topic_pattern: "module/v1/ff/{module_id}/factsheet"
    direction: "inbound"
    qos: 1
    retain: true
    
  # USAGE EXAMPLES (mehrere Beispiele für verschiedene Module)
  usage_examples:
    - description: "HBW - Hochregallager"
      topic: "module/v1/ff/SVR3QA0022/factsheet"
      payload:
        module_id: "SVR3QA0022"
        name: "HBW"
        type: "Storage"
        sub_type: "HBW"
        description: "Hochregallager für Werkstück-Lagerung und -Entnahme"
        ip_addresses: ["192.168.0.80", "192.168.0.81", "192.168.0.82", "192.168.0.83"]
        commands: ["PICK", "DROP", "STORE"]
        enabled: true
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:00:00Z"
        
    - description: "MILL - Fräsmodul"
      topic: "module/v1/ff/SVR3QA2098/factsheet"
      payload:
        module_id: "SVR3QA2098"
        name: "MILL"
        type: "Processing"
        sub_type: "MILL"
        description: "Fräsmodul für Werkstück-Bearbeitung"
        ip_addresses: ["192.168.0.40", "192.168.0.41", "192.168.0.42", "192.168.0.43", "192.168.0.44", "192.168.0.45"]
        commands: ["PICK", "MILL", "DROP"]
        enabled: true
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:05:00Z"
        
    - description: "DRILL - Bohrmodul"
      topic: "module/v1/ff/SVR4H76449/factsheet"
      payload:
        module_id: "SVR4H76449"
        name: "DRILL"
        type: "Processing"
        sub_type: "DRILL"
        description: "Bohrmodul für Werkstück-Bearbeitung"
        ip_addresses: ["192.168.0.50", "192.168.0.51", "192.168.0.52", "192.168.0.53", "192.168.0.54", "192.168.0.55"]
        commands: ["PICK", "DRILL", "DROP"]
        enabled: true
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:10:00Z"
        
    - description: "AIQS - Qualitätsprüfung"
      topic: "module/v1/ff/SVR4H76530/factsheet"
      payload:
        module_id: "SVR4H76530"
        name: "AIQS"
        type: "Quality-Control"
        sub_type: "AIQS"
        description: "KI-basierte Qualitätsprüfung"
        ip_addresses: ["192.168.0.70", "192.168.0.71", "192.168.0.72", "192.168.0.73", "192.168.0.74", "192.168.0.75"]
        commands: ["PICK", "DROP", "CHECK_QUALITY"]
        enabled: true
        version: "1.3.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:15:00Z"
        
    - description: "CHRG - Ladestation"
      topic: "module/v1/ff/CHRG0/factsheet"
      payload:
        module_id: "CHRG0"
        name: "CHRG"
        type: "Charging"
        sub_type: "CHRG"
        description: "Ladestation für FTS-Akkus"
        ip_addresses: ["192.168.0.65"]
        commands: ["start_charging", "stop_charging", "get_status"]
        enabled: true
        version: "1.0.0"
        manufacturer: "Fischertechnik"
        timestamp: "2025-08-29T10:20:00Z"
