metadata:
  category: MODULE
  description: Generated order Templates
  generated: true
  icon: 🔗
  last_updated: '2025-08-29'
  source: module_config.yml
  sub_category: Order
  version: 3.0.0
templates:
  module/v1/ff/CHRG0/order:
    category: MODULE
    description: Module CHRG0 Order
    examples:
    - command: start_charging
      module_id: CHRG0
      parameters: {}
      timestamp: '2025-08-19T09:13:34.483Z'
    module: CHRG0
    sub_category: Order
    template_structure:
      command: '[start_charging, stop_charging, get_status]'
      module_id: '[CHRG0]'
      parameters: <object>
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - module_id muss in [CHRG0] sein
    - command muss in [start_charging, stop_charging, get_status] sein
  module/v1/ff/SVR3QA0022/order:
    category: MODULE
    description: Module SVR3QA0022 Order
    examples:
    - command: PICK
      module_id: SVR3QA0022
      parameters: {}
      timestamp: '2025-08-19T09:13:34.483Z'
    module: SVR3QA0022
    sub_category: Order
    template_structure:
      command: '[PICK, DROP, STORE]'
      module_id: '[SVR3QA0022]'
      parameters: <object>
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - module_id muss in [SVR3QA0022] sein
    - command muss in [PICK, DROP, STORE] sein
  module/v1/ff/SVR3QA2098/order:
    category: MODULE
    description: Module SVR3QA2098 Order
    examples:
    - command: PICK
      module_id: SVR3QA2098
      parameters: {}
      timestamp: '2025-08-19T09:13:34.483Z'
    module: SVR3QA2098
    sub_category: Order
    template_structure:
      command: '[PICK, MILL, DROP]'
      module_id: '[SVR3QA2098]'
      parameters: <object>
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - module_id muss in [SVR3QA2098] sein
    - command muss in [PICK, MILL, DROP] sein
  module/v1/ff/SVR4H73275/order:
    category: MODULE
    description: Module SVR4H73275 Order
    examples:
    - command: PICK
      module_id: SVR4H73275
      parameters: {}
      timestamp: '2025-08-19T09:13:34.483Z'
    module: SVR4H73275
    sub_category: Order
    template_structure:
      command: '[PICK, DROP, INPUT_RGB, RGB_NFC]'
      module_id: '[SVR4H73275]'
      parameters: <object>
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - module_id muss in [SVR4H73275] sein
    - command muss in [PICK, DROP, INPUT_RGB, RGB_NFC] sein
  module/v1/ff/SVR4H76449/order:
    category: MODULE
    description: Module SVR4H76449 Order
    examples:
    - command: PICK
      module_id: SVR4H76449
      parameters: {}
      timestamp: '2025-08-19T09:13:34.483Z'
    module: SVR4H76449
    sub_category: Order
    template_structure:
      command: '[PICK, DRILL, DROP]'
      module_id: '[SVR4H76449]'
      parameters: <object>
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - module_id muss in [SVR4H76449] sein
    - command muss in [PICK, DRILL, DROP] sein
  module/v1/ff/SVR4H76530/order:
    category: MODULE
    description: Module SVR4H76530 Order
    examples:
    - command: PICK
      module_id: SVR4H76530
      parameters: {}
      timestamp: '2025-08-19T09:13:34.483Z'
    module: SVR4H76530
    sub_category: Order
    template_structure:
      command: '[PICK, DROP, CHECK_QUALITY]'
      module_id: '[SVR4H76530]'
      parameters: <object>
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - module_id muss in [SVR4H76530] sein
    - command muss in [PICK, DROP, CHECK_QUALITY] sein
