metadata:
  category: MODULE
  description: MODULE Order Templates
  icon: 📋
  last_updated: '2025-08-29'
  sub_category: Order
  version: 3.0.0
templates:
  fts/v1/ff/5iO4/order:
    category: MODULE
    description: FTS Navigation Commands
    examples:
    - action:
        command: findInitialDockPosition
        id: 12345678-1234-1234-1234-123456789abc
        metadata:
          nodeId: SVR4H73275
      orderId: 87654321-4321-4321-4321-cba987654321
      orderUpdateId: 1
      serialNumber: 5iO4
      timestamp: '2025-08-28T12:00:00.000Z'
    - action:
        command: startCharging
        id: 23456789-2345-2345-2345-234567890bcd
        metadata: {}
      orderId: 98765432-5432-5432-5432-dcb098765432
      orderUpdateId: 2
      serialNumber: 5iO4
      timestamp: '2025-08-28T12:01:00.000Z'
    module: 5iO4
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: <string>
      serialNumber: '[5iO4]'
      timestamp: <datetime>
    ui_config:
      commands:
        factsheetRequest:
          color: secondary
          help: FTS Status abfragen
          icon: 🔄
          text: 🔄 Status abfragen
        findInitialDockPosition:
          color: primary
          help: FTS fährt zum Wareneingang (Initialisierung)
          icon: 🚗
          text: 🚗 Docke an
        startCharging:
          color: primary
          help: FTS fährt zur Charging Station
          icon: 🔋
          text: 🔋 FTS laden
        stopCharging:
          color: primary
          help: FTS stoppt das Laden
          icon: ⏹️
          text: ⏹️ Laden beenden
      module_id: 5iO4
      module_name: FTS
      state_machine_notes: 'FTS verwendet einen Zustandsautomaten:

        - Docke an: Nur nach Initialisierung verfügbar

        - Laden/Laden beenden: Gegenseitig ausschließend

        - Status-Abfrage: Für dynamische Button-Aktivierung (später)

        '
      success_message: FTS-Befehl erfolgreich gesendet
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - serialNumber muss in [5iO4] sein
  module/v1/ff/SVR3QA0022/order:
    category: MODULE
    description: Module SVR3QA0022 Order
    examples:
    - action:
        command: DROP
        id: 2ecc8911-1ce4-44d4-bc1a-d9574ef62464
        metadata:
          type: RED
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 1
      serialNumber: SVR3QA0022
      timestamp: '2025-08-19T09:16:26.706Z'
    - action:
        command: DROP
        id: 536f525c-ecf8-49af-a418-847ac2d4166c
        metadata:
          type: BLUE
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 1
      serialNumber: SVR3QA0022
      timestamp: '2025-08-20T09:59:24.233Z'
    - action:
        command: DROP
        id: f9abe292-91fa-4857-80c2-4f6855df8cc2
        metadata:
          type: BLUE
      orderId: b0c9a823-255d-458a-a409-1052cc725aac
      orderUpdateId: 1
      serialNumber: SVR3QA0022
      timestamp: '2025-08-20T09:58:36.067Z'
    - action:
        command: DROP
        id: c7e6f4dc-16ce-4463-8ef8-bf6a2f2d2c48
        metadata:
          type: BLUE
      orderId: a73e60cf-a116-4dcf-b2d1-3797b6f96912
      orderUpdateId: 1
      serialNumber: SVR3QA0022
      timestamp: '2025-08-20T09:57:53.427Z'
    - action:
        command: DROP
        id: ce4e7ca5-3ddd-40b3-b886-45b3d0e9e033
        metadata:
          type: BLUE
      orderId: 598cba14-5cb5-43e7-b8cc-530d87d2cfa3
      orderUpdateId: 1
      serialNumber: SVR3QA0022
      timestamp: '2025-08-19T09:28:39.456Z'
    module: SVR3QA0022
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: '[1, 3]'
      serialNumber: '[SVR3QA0022]'
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - serialNumber muss in [SVR3QA0022] sein
    - orderUpdateId muss in [1, 3] sein
  module/v1/ff/SVR3QA2098/order:
    category: MODULE
    description: Module SVR3QA2098 Order
    examples:
    - action:
        command: DROP
        id: ea84b176-0945-4609-8c17-ddcebb69b4fe
        metadata:
          type: RED
          workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 5
      serialNumber: SVR3QA2098
      timestamp: '2025-08-19T09:17:44.936Z'
    - action:
        command: MILL
        id: 3c1ea434-2ab5-477a-9b52-a436518b9cb8
        metadata:
          duration: 5
          type: RED
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 4
      serialNumber: SVR3QA2098
      timestamp: '2025-08-19T09:17:34.757Z'
    - action:
        command: PICK
        id: 683a526a-bf99-4d5a-be21-4efd3c88792f
        metadata:
          type: RED
          workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 3
      serialNumber: SVR3QA2098
      timestamp: '2025-08-19T09:17:25.211Z'
    - action:
        command: DROP
        id: 7ee2a215-a28b-484b-98d0-cea622bbc6d8
        metadata:
          type: BLUE
          workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 11
      serialNumber: SVR3QA2098
      timestamp: '2025-08-20T10:04:37.373Z'
    - action:
        command: MILL
        id: b4b406d2-e43a-48a2-8e37-9e7dd373b013
        metadata:
          duration: 5
          type: BLUE
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 9
      serialNumber: SVR3QA2098
      timestamp: '2025-08-20T10:03:54.269Z'
    module: SVR3QA2098
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: <string>
      serialNumber: '[SVR3QA2098]'
      timestamp: <datetime>
    ui_config:
      commands:
        DROP:
          color: primary
          help: Werkstück ablegen
          icon: 📥
          text: 📥 DROP
        MILL:
          color: primary
          help: Werkstück fräsen
          icon: ⚙️
          text: ⚙️ MILL
        PICK:
          color: primary
          help: Werkstück aufnehmen
          icon: 📤
          text: 📤 PICK
      module_id: SVR3QA2098
      module_name: MILL
      success_message: 'MILL-Befehl erfolgreich gesendet mit orderUpdateId: {orderUpdateId}'
      workpiece_selection:
        colors:
        - WHITE
        - RED
        - BLUE
        default_color: WHITE
        options:
          BLUE:
          - B1
          - B2
          - B3
          - B4
          - B5
          - B6
          - B7
          - B8
          RED:
          - R1
          - R2
          - R3
          - R4
          - R5
          - R6
          - R7
          - R8
          WHITE:
          - W1
          - W2
          - W3
          - W4
          - W5
          - W6
          - W7
          - W8
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - serialNumber muss in [SVR3QA2098] sein
  module/v1/ff/SVR4H73275/order:
    category: MODULE
    description: Module SVR4H73275 Order
    examples:
    - action:
        command: PICK
        id: 327784cd-6abc-4a0b-870e-713694fdb1dd
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755595028336
            - code: 600
              ts: 1755595064912
            - code: 200
              ts: 1755595103032
            state: PROCESSED
            type: RED
            workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 11
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:18:41.187Z'
    - action:
        command: PICK
        id: 7d18d976-8a7d-4e81-9387-afa21020c25e
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755684009575
            - code: 700
              ts: 1755684133967
            - code: 600
              ts: 1755684243218
            - code: 200
              ts: 1755684356607
            - code: 100
              ts: 1755680183643
            - code: 300
              ts: 1755680212526
            state: PROCESSED
            type: BLUE
            workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 18
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T10:06:47.500Z'
    - action:
        command: PICK
        id: fbb6bd63-3eb1-4ef2-8618-f9036d468429
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755683962675
            - code: 700
              ts: 1755684076008
            - code: 600
              ts: 1755684164181
            - code: 200
              ts: 1755684273420
            - code: 100
              ts: 1755680106493
            - code: 300
              ts: 1755680137522
            state: PROCESSED
            type: BLUE
            workpieceId: 048989ca341290
      orderId: b0c9a823-255d-458a-a409-1052cc725aac
      orderUpdateId: 18
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T10:05:56.739Z'
    - action:
        command: PICK
        id: a940bc49-c77d-4269-948e-88e933adeb8e
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755683914567
            - code: 700
              ts: 1755684043123
            - code: 600
              ts: 1755684097304
            - code: 200
              ts: 1755684209410
            - code: 100
              ts: 1755680030880
            - code: 300
              ts: 1755680061499
            state: PROCESSED
            type: BLUE
            workpieceId: 04a189ca341290
      orderId: a73e60cf-a116-4dcf-b2d1-3797b6f96912
      orderUpdateId: 17
      serialNumber: SVR4H73275
      timestamp: '2025-08-20T10:04:58.236Z'
    - action:
        command: PICK
        id: 5692d8a0-bbc4-43a4-8d4f-d86f0c896abf
        metadata:
          workpiece:
            history:
            - code: 400
              ts: 1755595760241
            - code: 700
              ts: 1755595793651
            - code: 600
              ts: 1755595834892
            - code: 200
              ts: 1755595873063
            state: PROCESSED
            type: BLUE
            workpieceId: 047389ca341291
      orderId: 598cba14-5cb5-43e7-b8cc-530d87d2cfa3
      orderUpdateId: 15
      serialNumber: SVR4H73275
      timestamp: '2025-08-19T09:31:30.940Z'
    module: SVR4H73275
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: <string>
      serialNumber: '[SVR4H73275]'
      timestamp: <datetime>
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - serialNumber muss in [SVR4H73275] sein
  module/v1/ff/SVR4H76449/order:
    category: MODULE
    description: Module SVR4H76449 Order
    examples:
    - action:
        command: DROP
        id: c4c9e23a-3d77-4c4e-9cbb-36987eb10d76
        metadata:
          type: BLUE
          workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 6
      serialNumber: SVR4H76449
      timestamp: '2025-08-20T10:02:46.349Z'
    - action:
        command: DRILL
        id: 1a75e423-c60d-4db8-9f82-9b1e448798f6
        metadata:
          duration: 5
          type: BLUE
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 4
      serialNumber: SVR4H76449
      timestamp: '2025-08-20T10:02:04.046Z'
    - action:
        command: PICK
        id: bede4ff9-9f7d-4032-a17e-bc6aafa67d78
        metadata:
          type: BLUE
          workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 3
      serialNumber: SVR4H76449
      timestamp: '2025-08-20T10:01:53.773Z'
    - action:
        command: DROP
        id: 9db5c23c-7f66-4d13-af7f-e7f11a313973
        metadata:
          type: BLUE
          workpieceId: 048989ca341290
      orderId: b0c9a823-255d-458a-a409-1052cc725aac
      orderUpdateId: 6
      serialNumber: SVR4H76449
      timestamp: '2025-08-20T10:01:41.524Z'
    - action:
        command: DRILL
        id: 34ee3f75-432a-44c0-a094-e0384a71beee
        metadata:
          duration: 5
          type: BLUE
      orderId: b0c9a823-255d-458a-a409-1052cc725aac
      orderUpdateId: 4
      serialNumber: SVR4H76449
      timestamp: '2025-08-20T10:01:06.062Z'
    module: SVR4H76449
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: '[3, 4, 5, 6]'
      serialNumber: '[SVR4H76449]'
      timestamp: <datetime>
    ui_config:
      commands:
        DRILL:
          color: primary
          help: Werkstück bohren
          icon: ⚙️
          text: ⚙️ DRILL
        DROP:
          color: primary
          help: Werkstück ablegen
          icon: 📥
          text: 📥 DROP
        PICK:
          color: primary
          help: Werkstück aufnehmen
          icon: 📤
          text: 📤 PICK
      module_id: SVR4H76449
      module_name: DRILL
      success_message: 'DRILL-Befehl erfolgreich gesendet mit orderUpdateId: {orderUpdateId}'
      workpiece_selection:
        colors:
        - WHITE
        - RED
        - BLUE
        default_color: WHITE
        options:
          BLUE:
          - B1
          - B2
          - B3
          - B4
          - B5
          - B6
          - B7
          - B8
          RED:
          - R1
          - R2
          - R3
          - R4
          - R5
          - R6
          - R7
          - R8
          WHITE:
          - W1
          - W2
          - W3
          - W4
          - W5
          - W6
          - W7
          - W8
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - serialNumber muss in [SVR4H76449] sein
    - orderUpdateId muss in [3, 4, 5, 6] sein
  module/v1/ff/SVR4H76530/order:
    category: MODULE
    description: Module SVR4H76530 Order
    examples:
    - action:
        command: DROP
        id: 6d9c53fd-c911-407e-be14-1e0d0a93b5bc
        metadata:
          type: RED
          workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 9
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:23.042Z'
    - action:
        command: CHECK_QUALITY
        id: 7b25fdfb-4a9e-419d-836c-c4348d9d9fd3
        metadata:
          type: RED
          workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 8
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:14.868Z'
    - action:
        command: PICK
        id: 35d69089-2162-41b1-8d14-ef4d3e06347a
        metadata:
          type: RED
          workpieceId: 040a8dca341291
      orderId: 8ae07a6e-d058-48de-9b4d-8d0176622abc
      orderUpdateId: 7
      serialNumber: SVR4H76530
      timestamp: '2025-08-19T09:18:06.708Z'
    - action:
        command: DROP
        id: f38e4d79-859b-4f41-aec4-50cb60f3dd9e
        metadata:
          type: BLUE
          workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 16
      serialNumber: SVR4H76530
      timestamp: '2025-08-20T10:06:29.715Z'
    - action:
        command: CHECK_QUALITY
        id: 4030fb15-9ffa-449c-b510-dc61b0184e48
        metadata:
          type: BLUE
          workpieceId: 047389ca341291
      orderId: 6bb6f7a4-90f7-4ba2-bb60-e0be0202d014
      orderUpdateId: 14
      serialNumber: SVR4H76530
      timestamp: '2025-08-20T10:05:47.423Z'
    module: SVR4H76530
    sub_category: Order
    template_structure:
      action: <string>
      orderId: <string>
      orderUpdateId: <string>
      serialNumber: '[SVR4H76530]'
      timestamp: <datetime>
    ui_config:
      commands:
        CHECK_QUALITY:
          color: primary
          help: Qualität prüfen
          icon: 🔍
          text: 🔍 CHECK_QUALITY
        DROP:
          color: primary
          help: Werkstück ablegen
          icon: 📥
          text: 📥 DROP
        PICK:
          color: primary
          help: Werkstück aufnehmen
          icon: 📤
          text: 📤 PICK
      module_id: SVR4H76530
      module_name: AIQS
      success_message: 'AIQS-Befehl erfolgreich gesendet mit orderUpdateId: {orderUpdateId}'
      workpiece_selection:
        colors:
        - WHITE
        - RED
        - BLUE
        default_color: WHITE
        options:
          BLUE:
          - B1
          - B2
          - B3
          - B4
          - B5
          - B6
          - B7
          - B8
          RED:
          - R1
          - R2
          - R3
          - R4
          - R5
          - R6
          - R7
          - R8
          WHITE:
          - W1
          - W2
          - W3
          - W4
          - W5
          - W6
          - W7
          - W8
    validation_rules:
    - timestamp muss ISO 8601 Format haben
    - serialNumber muss in [SVR4H76530] sein
