metadata:
  category: MODULE
  description: Module State Message Template
  template_type: "message_structure_definition"
  last_updated: "2025-08-29"
  version: 3.0.0

# TEMPLATE: Message-Struktur-Definition
template:
  name: "module/state"
  description: "Module State - Message Structure Definition"
  semantic_purpose: "Aktuellen Zustand eines Moduls abfragen"
  
  # SYNTAX: Struktur der Nachricht
  structure:
    required_fields:
      - module_id
      - state
      - timestamp
    optional_fields:
      - status
      - details
    
    field_definitions:
      module_id:
        type: "string"
        pattern: "enum"
        description: "Serial Number des Moduls"
        validation: "must be valid module serial number"
        
      state:
        type: "string"
        pattern: "enum"
        description: "Aktueller Zustand des Moduls"
        validation: "must be valid module state"
        
      status:
        type: "string"
        pattern: "enum"
        description: "Status des Moduls"
        validation: "must be valid module status"
        
      details:
        type: "object"
        description: "Zusätzliche Zustandsdetails"
        validation: "optional object with additional information"
        
      timestamp:
        type: "string"
        pattern: "iso8601"
        description: "Zeitstempel"
        validation: "must be ISO 8601 format"
  
  # SEMANTICS: Validierungsregeln
  validation_rules:
    - "timestamp muss ISO 8601 Format haben"
    - "module_id muss gültige Serial Number sein"
    - "state muss gültiger Modul-Zustand sein"
    - "status muss gültiger Status sein"
    - "details ist optional"
  
  # VARIABLE FIELDS: Enum-Werte für Generierung
  variable_fields:
    module_id:
      type: "enum"
      values: ["SVR3QA0022", "SVR4H76449", "SVR3QA2098", "SVR4H76530", "SVR4H73275", "CHRG0"]
      description: "Serial Number des Moduls"
      
    state:
      type: "enum"
      values: ["IDLE", "BUSY", "ERROR", "MAINTENANCE", "OFFLINE"]
      description: "Aktueller Zustand des Moduls"
      
    status:
      type: "enum"
      values: ["OK", "WARNING", "ERROR", "UNKNOWN"]
      description: "Status des Moduls"
  
  # MQTT INTEGRATION
  mqtt:
    topic_pattern: "module/v1/ff/{module_id}/state"
    direction: "bidirectional"
    qos: 1
    retain: false
    
  # USAGE EXAMPLES (mehrere Beispiele für ENUM-Werte)
  usage_examples:
    - description: "Modul im Leerlauf (IDLE)"
      topic: "module/v1/ff/SVR3QA0022/state"
      payload:
        module_id: "SVR3QA0022"
        state: "IDLE"
        status: "OK"
        timestamp: "2025-08-29T10:00:00Z"
        
    - description: "Modul beschäftigt (BUSY)"
      topic: "module/v1/ff/SVR3QA2098/state"
      payload:
        module_id: "SVR3QA2098"
        state: "BUSY"
        status: "OK"
        details:
          current_operation: "MILL"
          progress: 75
        timestamp: "2025-08-29T10:05:00Z"
        
    - description: "Modul mit Fehler (ERROR)"
      topic: "module/v1/ff/SVR4H76449/state"
      payload:
        module_id: "SVR4H76449"
        state: "ERROR"
        status: "ERROR"
        details:
          error_code: "E001"
          error_message: "Tool broken"
        timestamp: "2025-08-29T10:10:00Z"
        
    - description: "Modul in Wartung (MAINTENANCE)"
      topic: "module/v1/ff/SVR4H76530/state"
      payload:
        module_id: "SVR4H76530"
        state: "MAINTENANCE"
        status: "WARNING"
        details:
          maintenance_type: "scheduled"
          estimated_duration: "2 hours"
        timestamp: "2025-08-29T10:15:00Z"
        
    - description: "Modul offline (OFFLINE)"
      topic: "module/v1/ff/SVR4H73275/state"
      payload:
        module_id: "SVR4H73275"
        state: "OFFLINE"
        status: "ERROR"
        details:
          reason: "network_disconnect"
          last_seen: "2025-08-29T10:12:00Z"
        timestamp: "2025-08-29T10:20:00Z"
