name: Run pytest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install streamlit
        pip install pyyaml
        pip install pathlib
    
    - name: Run shopfloor layout smoke tests
      run: |
        python tests/test_shopfloor_layout_smoke.py
    
    - name: Run shopfloor layout click tests
      run: |
        python tests/test_shopfloor_layout_click.py
    
    - name: Run all pytest tests
      run: |
        python -m pytest tests/ -v
